Repository kiali/kiali-operator, pull requests merged in 2020-09, with the labels that each got.

#126 Add revision field into istio config
  deploy/kiali/kiali_cr.yaml
  roles/default/kiali-deploy/defaults/main.yml
Labels: backend changes required

#127 Rename Revision by ConfigMapName setting to kiali CR
  deploy/kiali/kiali_cr.yaml
  roles/default/kiali-deploy/defaults/main.yml
Labels: backend changes required

#128 Add namespace field in each istio component health
  deploy/kiali/kiali_cr.yaml
  roles/default/kiali-deploy/defaults/main.yml
Labels: backend changes required

#130 new community metadata for v1.24.0
  manifests/kiali-community/1.24.0/kiali.crd.yaml
  manifests/kiali-community/1.24.0/kiali.monitoringdashboards.crd.yaml
  manifests/kiali-community/1.24.0/kiali.v1.24.0.clusterserviceversion.yaml
  manifests/kiali-community/kiali.package.yaml
  manifests/kiali-upstream/1.24.0/kiali.crd.yaml
  manifests/kiali-upstream/1.24.0/kiali.monitoringdashboards.crd.yaml
  manifests/kiali-upstream/1.24.0/kiali.v1.24.0.clusterserviceversion.yaml
  manifests/kiali-upstream/kiali.package.yaml
Labels: team/saturn

#131 [v1.12 / v1.0] Use new OpenShift interface for service serving certificates
  roles/v1.0/kiali-deploy/tasks/main.yml
  roles/v1.0/kiali-deploy/tasks/openshift/os-main.yml
  roles/v1.0/kiali-deploy/templates/openshift/cabundle.yaml
  roles/v1.0/kiali-deploy/templates/openshift/deployment.yaml
  roles/v1.0/kiali-deploy/templates/openshift/service.yaml
  roles/v1.0/kiali-remove/tasks/main.yml
  roles/v1.12/kiali-deploy/tasks/main.yml
  roles/v1.12/kiali-deploy/tasks/openshift/os-main.yml
  roles/v1.12/kiali-deploy/templates/openshift/cabundle.yaml
  roles/v1.12/kiali-deploy/templates/openshift/deployment.yaml
  roles/v1.12/kiali-deploy/templates/openshift/service.yaml
  roles/v1.12/kiali-remove/tasks/main.yml
Labels: team/saturn

#138 [v1.24] the permissions are out-of-date.
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
Labels: team/saturn

#139 the permissions here are out-of-date.
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
Labels: backport/v1.24, team/saturn

#137 do not rely on the name of the clusterrole to do a can_i check
  roles/default/kiali-deploy/tasks/main.yml
Labels: team/saturn

#141 The current test will only test the implicit flow - need special signing_key to enable that
  molecule/openid-test/kiali-cr.yaml
Labels: backport/v1.24, team/saturn

#142 [v1.24] The current test will only test the implicit flow - need special signing_key to enable that
  molecule/openid-test/kiali-cr.yaml
Labels: team/saturn

#143 sort the list of accessible namespaces (#135)
  roles/default/kiali-deploy/tasks/main.yml
Labels: team/saturn

#146 correct test by using accurate settings
  molecule/null-cr-values-test/kiali-cr.yaml
Labels: backport/v1.24, team/saturn

#147 [v1.24] correct test by using accurate settings
  molecule/null-cr-values-test/kiali-cr.yaml
Labels: team/saturn

#150 fix component_status
  deploy/kiali/kiali_cr.yaml
  roles/default/kiali-deploy/defaults/main.yml
  roles/v1.24/kiali-deploy/defaults/main.yml
Labels: backport/v1.24, team/saturn

#149 [v1.24] fix component_status
  deploy/kiali/kiali_cr.yaml
  roles/default/kiali-deploy/defaults/main.yml
  roles/v1.24/kiali-deploy/defaults/main.yml
Labels: team/saturn

#151 [v1.24] updated kiali-ossm CSV metadata
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
Labels: team/saturn

#144 Remove ServiceMeshPolicy and SMRbacConfig for Maistra installations
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
  roles/default/kiali-deploy/templates/openshift/role-viewer.yaml
  roles/default/kiali-deploy/templates/openshift/role.yaml
  roles/v1.24/kiali-deploy/templates/openshift/role-viewer.yaml
  roles/v1.24/kiali-deploy/templates/openshift/role.yaml
Labels: backend changes required
