Repository kiali/kiali-operator, pull requests merged in 2020-10, with the labels that each got.

#154 do not deploy dashboard resources if dashboards are disabled
  molecule/config-values-test/converge.yml
  roles/default/kiali-deploy/tasks/main.yml
Labels: enhancement, team/saturn

#156 molecule tests - allow dump logs on error to be turned off
  molecule/default/cleanup.yml
Labels: team/saturn

#157 [v1.24] backport support for dashboard disable flag
  deploy/kiali/kiali_cr.yaml
  molecule/config-values-test/converge.yml
  roles/default/kiali-deploy/defaults/main.yml
  roles/default/kiali-deploy/tasks/main.yml
  roles/v1.24/kiali-deploy/defaults/main.yml
  roles/v1.24/kiali-deploy/tasks/main.yml
Labels: backend changes required

#140 Adding permissions for fetching proxy-status
  manifests/kiali-community/1.25.0/kiali.v1.25.0.clusterserviceversion.yaml
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
  manifests/kiali-upstream/1.25.0/kiali.v1.25.0.clusterserviceversion.yaml
  roles/default/kiali-deploy/templates/kubernetes/role-viewer.yaml
  roles/default/kiali-deploy/templates/kubernetes/role.yaml
  roles/default/kiali-deploy/templates/openshift/role-viewer.yaml
  roles/default/kiali-deploy/templates/openshift/role.yaml
Labels: backend changes required

#159 Revert "Change kiali-ossm manifest to remove support to maistra crds"
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
Labels: backport/v1.24

#161 more notes about developing operator
  DEVELOPING.adoc
Labels: team/saturn

#155 Add molecule tests for the Kiali API
  molecule/api-test/apps.test.yaml
  molecule/api-test/cleanup.yml
  molecule/api-test/config.test.yaml
  molecule/api-test/converge.yml
  molecule/api-test/create-simple-mesh.yml
  molecule/api-test/delete-simple-mesh.yml
  molecule/api-test/graph.test.yaml
  molecule/api-test/health.test.yaml
  molecule/api-test/healthz.test.yaml
  molecule/api-test/istio-config.test.yaml
  molecule/api-test/istio-permissions.test.yaml
  molecule/api-test/istio-status.test.yaml
  molecule/api-test/kiali-cr.yaml
  molecule/api-test/metrics.test.yaml
  molecule/api-test/molecule.yml
  molecule/api-test/namespaces.test.yaml
  molecule/api-test/services.test.yaml
  molecule/api-test/status.test.yaml
  molecule/api-test/tls.test.yaml
  molecule/api-test/validations.test.yaml
  molecule/api-test/workloads.test.yaml
  molecule/default/cleanup.yml
  molecule/default/dump-logs.yml
Labels: team/saturn

#163 [v1.24] turn off dependent resource watching
  watches.yaml
Labels: team/saturn

#164 turn off dependent resource watching
  watches.yaml
Labels: backport/v1.24, team/saturn

#167 remove buggy checks - these cause problems
  roles/default/kiali-deploy/tasks/main.yml
  roles/v1.24/kiali-deploy/tasks/main.yml
Labels: backport/v1.24, team/saturn

#166 [v1.24] remove buggy checks - these cause problems
  roles/default/kiali-deploy/tasks/main.yml
  roles/v1.24/kiali-deploy/tasks/main.yml
Labels: team/saturn

#168 Enable dependency resource watching but be able to turn off reconciliation in case of emergency
  playbooks/kiali-deploy.yml
  watches.yaml
Labels: backport/v1.24, team/saturn

#169 [v1.24] Enable dependency resource watching but be able to turn off reconciliation in case of emergency
  playbooks/kiali-deploy.yml
  watches.yaml
Labels: team/saturn

#171 convert some vars to bool during conditional checks
  roles/default/kiali-deploy/tasks/kubernetes/k8s-main.yml
  roles/default/kiali-deploy/tasks/main.yml
  roles/default/kiali-deploy/tasks/openshift/os-main.yml
  roles/default/kiali-deploy/tasks/process-additional-roles.yml
  roles/default/kiali-deploy/templates/kubernetes/deployment.yaml
  roles/default/kiali-deploy/templates/kubernetes/rolebinding.yaml
  roles/default/kiali-deploy/templates/kubernetes/service.yaml
  roles/default/kiali-deploy/templates/openshift/deployment.yaml
  roles/default/kiali-deploy/templates/openshift/rolebinding.yaml
  roles/default/kiali-deploy/templates/openshift/service.yaml
  roles/v1.24/kiali-deploy/tasks/kubernetes/k8s-main.yml
  roles/v1.24/kiali-deploy/tasks/main.yml
  roles/v1.24/kiali-deploy/tasks/openshift/os-main.yml
  roles/v1.24/kiali-deploy/tasks/process-additional-roles.yml
  roles/v1.24/kiali-deploy/templates/kubernetes/deployment.yaml
  roles/v1.24/kiali-deploy/templates/kubernetes/rolebinding.yaml
  roles/v1.24/kiali-deploy/templates/kubernetes/service.yaml
  roles/v1.24/kiali-deploy/templates/openshift/deployment.yaml
  roles/v1.24/kiali-deploy/templates/openshift/rolebinding.yaml
  roles/v1.24/kiali-deploy/templates/openshift/service.yaml
Labels: backport/v1.24, team/saturn

#170 [v1.24] convert some vars to bool during conditional checks
  roles/default/kiali-deploy/tasks/kubernetes/k8s-main.yml
  roles/default/kiali-deploy/tasks/main.yml
  roles/default/kiali-deploy/tasks/openshift/os-main.yml
  roles/default/kiali-deploy/tasks/process-additional-roles.yml
  roles/default/kiali-deploy/templates/kubernetes/deployment.yaml
  roles/default/kiali-deploy/templates/kubernetes/rolebinding.yaml
  roles/default/kiali-deploy/templates/kubernetes/service.yaml
  roles/default/kiali-deploy/templates/openshift/deployment.yaml
  roles/default/kiali-deploy/templates/openshift/rolebinding.yaml
  roles/default/kiali-deploy/templates/openshift/service.yaml
  roles/v1.24/kiali-deploy/tasks/kubernetes/k8s-main.yml
  roles/v1.24/kiali-deploy/tasks/main.yml
  roles/v1.24/kiali-deploy/tasks/openshift/os-main.yml
  roles/v1.24/kiali-deploy/tasks/process-additional-roles.yml
  roles/v1.24/kiali-deploy/templates/kubernetes/deployment.yaml
  roles/v1.24/kiali-deploy/templates/kubernetes/rolebinding.yaml
  roles/v1.24/kiali-deploy/templates/kubernetes/service.yaml
  roles/v1.24/kiali-deploy/templates/openshift/deployment.yaml
  roles/v1.24/kiali-deploy/templates/openshift/rolebinding.yaml
  roles/v1.24/kiali-deploy/templates/openshift/service.yaml
Labels: team/saturn

#173 [v1.24] add "versions" list to MonitoringDashboard CRD in ossm metadata
  manifests/kiali-ossm/manifests/kiali.monitoringdashboards.crd.yaml
Labels: team/saturn

#174 k8s kind "extensions/v1beta1 Ingress" is deprecated in favor of "networking.k8s.io/v1beta1 Ingress"
  manifests/kiali-community/1.26.0/kiali.v1.26.0.clusterserviceversion.yaml
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
  manifests/kiali-upstream/1.26.0/kiali.v1.26.0.clusterserviceversion.yaml
  roles/default/kiali-deploy/tasks/kubernetes/k8s-main.yml
  roles/default/kiali-deploy/templates/kubernetes/ingress.yaml
  roles/default/kiali-remove/tasks/main.yml
Labels: team/saturn

#176 fix up some comments
  deploy/kiali/kiali_cr.yaml
Labels: team/saturn

#177 clean up threescale from molecule tests
  DEVELOPING.adoc
  molecule/api-test/config.test.yaml
  molecule/null-cr-values-test/kiali-cr.yaml
Labels: team/saturn

#178 fix molecule test - no longer any mixer related things
  DEVELOPING.adoc
  molecule/api-test/config.test.yaml
Labels: team/saturn

#179 some more instructions on molecule testing
  DEVELOPING.adoc
Labels: team/saturn

#180 Support pod_labels setting.
  deploy/kiali/kiali_cr.yaml
  molecule/affinity-tolerations-resources-test/converge.yml
  molecule/affinity-tolerations-resources-test/set-affinity-tolerations-resources.yml
  molecule/null-cr-values-test/kiali-cr.yaml
  roles/default/kiali-deploy/defaults/main.yml
  roles/default/kiali-deploy/tasks/main.yml
  roles/default/kiali-deploy/templates/kubernetes/deployment.yaml
  roles/default/kiali-deploy/templates/openshift/deployment.yaml
Labels: team/saturn

#184 remind dev to build molecule image
  DEVELOPING.adoc
Labels: team/saturn

#185 OSSM-298 - Kiali operator supports disconnected mode
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
Labels: backport/v1.24, team/saturn

#186 [v1.24] OSSM-298 - Kiali operator supports disconnected mode
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
Labels: team/saturn

#165 Add defaults for `disable_rbac` OpenId configuration
  deploy/kiali/kiali_cr.yaml
  roles/default/kiali-deploy/defaults/main.yml
Labels: team/saturn
