Repository kiali/kiali-operator, pull requests merged in 2020-06, with the labels that each got.

#46 changes to run molecule tests on minikube
  molecule/accessible-namespaces-test/molecule.yml
  molecule/affinity-tolerations-resources-test/molecule.yml
  molecule/common/prepare-prometheus.yml
  molecule/common/tasks.yml
  molecule/common/unprepare-prometheus.yml
  molecule/config-values-test/molecule.yml
  molecule/default-namespace-test/molecule.yml
  molecule/default/molecule.yml
  molecule/metrics-test/playbook.yml
  molecule/null-cr-values-test/molecule.yml
  molecule/only-view-only-mode-test/molecule.yml
  molecule/roles-test/molecule.yml
  molecule/rolling-restart-test/molecule.yml
Labels: backend changes required, enhancement

#42 Add support for authentication through an OpenId provider
  deploy/kiali/kiali_cr.yaml
  roles/default/kiali-deploy/defaults/main.yml
  roles/default/kiali-deploy/tasks/main.yml
  roles/default/kiali-deploy/templates/openshift/oauth.yaml
Labels: enhancement

#59 Cluster roles/bindings have no namespace - remove the superfluous namespace settings
  roles/default/kiali-deploy/tasks/main.yml
  roles/default/kiali-deploy/tasks/remove-clusterroles.yml
  roles/default/kiali-remove/tasks/main.yml
  roles/default/kiali-remove/tasks/remove-clusterroles.yml
  roles/v1.0/kiali-deploy/tasks/main.yml
  roles/v1.0/kiali-remove/tasks/main.yml
  roles/v1.12/kiali-deploy/tasks/main.yml
  roles/v1.12/kiali-remove/tasks/main.yml
Labels: team/saturn

#61 remove tests that check for app console links - they are no longer created
  molecule/os-console-links-test/playbook.yml
Labels: team/saturn

#62 be able to run the Molecule tests on platforms that only have podman - pass DORP to the molecule config
  molecule/accessible-namespaces-test/molecule.yml
  molecule/affinity-tolerations-resources-test/molecule.yml
  molecule/asserts/ldap-test/assert-ldap-access.yml
  molecule/config-values-test/molecule.yml
  molecule/default-namespace-test/molecule.yml
  molecule/default/molecule.yml
  molecule/docker/Dockerfile
  molecule/ldap-test/destroy-ldap.yml
  molecule/ldap-test/kiali-cr.yaml
  molecule/ldap-test/ldap-deployment.yaml
  molecule/ldap-test/ldap-service.yaml
  molecule/ldap-test/molecule.yml
  molecule/ldap-test/playbook.yml
  molecule/ldap-test/prepare-ldap.yml
  molecule/metrics-test/molecule.yml
  molecule/null-cr-values-test/molecule.yml
  molecule/only-view-only-mode-test/molecule.yml
  molecule/openid-test/molecule.yml
  molecule/os-console-links-test/molecule.yml
  molecule/requirements.txt
  molecule/roles-test/molecule.yml
  molecule/rolling-restart-test/molecule.yml
  molecule/token-test/molecule.yml
Labels: backend changes required, do not merge

#56 Use new OpenShift interface for service serving certificates
  deploy/kiali/kiali_cr_dev_servicemesh.yaml
  roles/default/kiali-deploy/tasks/main.yml
  roles/default/kiali-deploy/tasks/openshift/os-main.yml
  roles/default/kiali-deploy/templates/openshift/cabundle.yaml
  roles/default/kiali-deploy/templates/openshift/deployment.yaml
  roles/default/kiali-deploy/templates/openshift/service.yaml
  roles/default/kiali-remove/tasks/main.yml
Labels: team/saturn
