Repository kiali/kiali-operator, pull requests merged in 2020-04, with the labels that each got.

#3 move up to 0.17.0 of the sdk - needed for arm64 support
  Makefile
  build/Dockerfile
Labels: enhancement

#16 Truncate version label to the k8s maximum of 63 when appropriate.
  molecule/config-values-test/molecule.yml
  molecule/config-values-test/playbook.yml
  molecule/config-values-test/set-kiali-cr.yml
  molecule/config-values-test/set-version-label.yml
  roles/default/kiali-deploy/tasks/main.yml
  roles/v1.0/kiali-deploy/tasks/main.yml
  roles/v1.12/kiali-deploy/tasks/main.yml
Labels: backport/v1.12, bug

#17 [v1.12] Truncate version label to the k8s maximum of 63 when appropriate.
  molecule/config-values-test/molecule.yml
  molecule/config-values-test/playbook.yml
  molecule/config-values-test/set-kiali-cr.yml
  molecule/config-values-test/set-version-label.yml
  roles/default/kiali-deploy/tasks/main.yml
  roles/v1.0/kiali-deploy/tasks/main.yml
  roles/v1.12/kiali-deploy/tasks/main.yml
Labels: bug

#20 Change iter8 to iter_8 to please ansible operator
  deploy/kiali/kiali_cr.yaml
  roles/default/kiali-deploy/defaults/main.yml
Labels: backend changes required
