Repository kiali/kiali-operator, pull requests merged in 2020-07, with the labels that each got.

#64 add test to see cabundle is created/destroyed appropriately
  molecule/default-namespace-test/playbook.yml
Labels: team/saturn

#63 [v1.12 / v1.0] Use new OpenShift interface for service serving certificates
  roles/v1.0/kiali-deploy/tasks/main.yml
  roles/v1.0/kiali-deploy/tasks/openshift/os-main.yml
  roles/v1.0/kiali-deploy/templates/openshift/cabundle.yaml
  roles/v1.0/kiali-deploy/templates/openshift/deployment.yaml
  roles/v1.0/kiali-deploy/templates/openshift/service.yaml
  roles/v1.0/kiali-remove/tasks/main.yml
  roles/v1.12/kiali-deploy/tasks/main.yml
  roles/v1.12/kiali-deploy/tasks/openshift/os-main.yml
  roles/v1.12/kiali-deploy/templates/openshift/cabundle.yaml
  roles/v1.12/kiali-deploy/templates/openshift/deployment.yaml
  roles/v1.12/kiali-deploy/templates/openshift/service.yaml
  roles/v1.12/kiali-remove/tasks/main.yml
Labels: team/saturn

#22 convert to new olm bundle format and use the new RELATED_IMAGE_xyz env var
  .travis.yml
  manifests/kiali-ossm/1.0.10/kiali.v1.0.10.clusterserviceversion.yaml
  manifests/kiali-ossm/1.0.11/kiali.crd.yaml
  manifests/kiali-ossm/1.0.11/kiali.monitoringdashboards.crd.yaml
  manifests/kiali-ossm/1.0.12/kiali.crd.yaml
  manifests/kiali-ossm/1.0.12/kiali.monitoringdashboards.crd.yaml
  manifests/kiali-ossm/1.0.12/kiali.v1.0.12.clusterserviceversion.yaml
  manifests/kiali-ossm/1.0.5/kiali.crd.yaml
  manifests/kiali-ossm/1.0.5/kiali.monitoringdashboards.crd.yaml
  manifests/kiali-ossm/1.0.5/kiali.v1.0.5.clusterserviceversion.yaml
  manifests/kiali-ossm/1.0.6/kiali.crd.yaml
  manifests/kiali-ossm/1.0.6/kiali.monitoringdashboards.crd.yaml
  manifests/kiali-ossm/1.0.6/kiali.v1.0.6.clusterserviceversion.yaml
  manifests/kiali-ossm/1.0.7/kiali.crd.yaml
  manifests/kiali-ossm/1.0.7/kiali.monitoringdashboards.crd.yaml
  manifests/kiali-ossm/1.0.7/kiali.v1.0.7.clusterserviceversion.yaml
  manifests/kiali-ossm/1.0.8/kiali.crd.yaml
  manifests/kiali-ossm/1.0.8/kiali.monitoringdashboards.crd.yaml
  manifests/kiali-ossm/1.0.8/kiali.v1.0.8.clusterserviceversion.yaml
  manifests/kiali-ossm/1.0.9/kiali.crd.yaml
  manifests/kiali-ossm/1.0.9/kiali.monitoringdashboards.crd.yaml
  manifests/kiali-ossm/1.0.9/kiali.v1.0.9.clusterserviceversion.yaml
  manifests/kiali-ossm/1.12.11/kiali.crd.yaml
  manifests/kiali-ossm/1.12.11/kiali.monitoringdashboards.crd.yaml
  manifests/kiali-ossm/1.12.11/kiali.v1.12.11.clusterserviceversion.yaml
  manifests/kiali-ossm/1.12.12/kiali.crd.yaml
  manifests/kiali-ossm/1.12.12/kiali.monitoringdashboards.crd.yaml
  manifests/kiali-ossm/1.12.12/kiali.v1.12.12.clusterserviceversion.yaml
  manifests/kiali-ossm/1.12.13/kiali.crd.yaml
  manifests/kiali-ossm/1.12.13/kiali.monitoringdashboards.crd.yaml
  manifests/kiali-ossm/1.12.13/kiali.v1.12.13.clusterserviceversion.yaml
  manifests/kiali-ossm/1.12.14/kiali.crd.yaml
  manifests/kiali-ossm/1.12.14/kiali.monitoringdashboards.crd.yaml
  manifests/kiali-ossm/1.12.14/kiali.v1.12.14.clusterserviceversion.yaml
  manifests/kiali-ossm/1.12.6/kiali.crd.yaml
  manifests/kiali-ossm/1.12.6/kiali.monitoringdashboards.crd.yaml
  manifests/kiali-ossm/1.12.6/kiali.v1.12.6.clusterserviceversion.yaml
  manifests/kiali-ossm/1.12.7/kiali.crd.yaml
  manifests/kiali-ossm/1.12.7/kiali.monitoringdashboards.crd.yaml
  manifests/kiali-ossm/1.12.7/kiali.v1.12.7.clusterserviceversion.yaml
  manifests/kiali-ossm/kiali-ossm.package.yaml
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
  manifests/kiali-ossm/manifests/kiali.crd.yaml
  manifests/kiali-ossm/manifests/kiali.monitoringdashboards.crd.yaml
  manifests/kiali-ossm/metadata/annotations.yaml
  playbooks/kiali-deploy.yml
Labels: team/saturn

#65 Molecule tests for validatio openid auth with `state` param
  molecule/openid-test/playbook.yml
Labels: team/saturn

#70 log the name/namespace of the CR that is being watched and processed by the playbook
  playbooks/kiali-deploy.yml
  playbooks/kiali-remove.yml
Labels: team/saturn

#73 Make sure travis has envsubst installed
  .travis.yml
Labels: team/saturn

#72 Enable travis build for ppc64le
  .travis.yml
Labels: backend changes required

#74 Molecule tests should dump the logs on failure
  molecule/README.md
  molecule/accessible-namespaces-test/converge.yml
  molecule/accessible-namespaces-test/molecule.yml
  molecule/affinity-tolerations-resources-test/converge.yml
  molecule/affinity-tolerations-resources-test/molecule.yml
  molecule/asserts/roles-test/ro_clusterrole_asserts.yml
  molecule/asserts/roles-test/ro_role_asserts.yml
  molecule/asserts/roles-test/rw_clusterrole_asserts.yml
  molecule/asserts/roles-test/rw_role_asserts.yml
  molecule/common/prepare-prometheus.yml
  molecule/common/tasks.yml
  molecule/common/wait_for_kiali_cr_changes.yml
  molecule/common/wait_for_kiali_running.yml
  molecule/config-values-test/converge.yml
  molecule/config-values-test/molecule.yml
  molecule/default-namespace-test/converge.yml
  molecule/default-namespace-test/molecule.yml
  molecule/default/cleanup.yml
  molecule/default/converge.yml
  molecule/default/destroy.yml
  molecule/default/molecule.yml
  molecule/default/prepare.yml
  molecule/docker/Dockerfile
  molecule/metrics-test/converge.yml
  molecule/metrics-test/molecule.yml
  molecule/null-cr-values-test/converge.yml
  molecule/null-cr-values-test/molecule.yml
  molecule/only-view-only-mode-test/converge.yml
  molecule/only-view-only-mode-test/molecule.yml
  molecule/openid-test/converge.yml
  molecule/openid-test/molecule.yml
  molecule/os-console-links-test/converge.yml
  molecule/os-console-links-test/molecule.yml
  molecule/requirements.txt
  molecule/roles-test/converge.yml
  molecule/roles-test/molecule.yml
  molecule/rolling-restart-test/converge.yml
  molecule/rolling-restart-test/molecule.yml
  molecule/token-test/converge.yml
  molecule/token-test/molecule.yml
  molecule/token-test/prepare-token.yml
Labels: team/saturn

#76 oauthclient is a cluster scoped resource - namespace should not be specified
  roles/default/kiali-deploy/templates/openshift/oauth.yaml
  roles/default/kiali-remove/tasks/main.yml
  roles/v1.0/kiali-deploy/templates/openshift/oauth.yaml
  roles/v1.0/kiali-remove/tasks/main.yml
  roles/v1.12/kiali-deploy/templates/openshift/oauth.yaml
  roles/v1.12/kiali-remove/tasks/main.yml
Labels: backend changes required

#79 bump to molecule 3.0.6
  molecule/docker/Dockerfile
Labels: enhancement, team/saturn

#80 be able to specify the pull policy - this might help speed up tests if using dev or released images
  molecule/accessible-namespaces-test/molecule.yml
  molecule/affinity-tolerations-resources-test/molecule.yml
  molecule/config-values-test/molecule.yml
  molecule/default-namespace-test/molecule.yml
  molecule/default/destroy.yml
  molecule/default/molecule.yml
  molecule/default/prepare.yml
  molecule/metrics-test/molecule.yml
  molecule/null-cr-values-test/molecule.yml
  molecule/only-view-only-mode-test/molecule.yml
  molecule/openid-test/molecule.yml
  molecule/os-console-links-test/molecule.yml
  molecule/roles-test/molecule.yml
  molecule/rolling-restart-test/molecule.yml
  molecule/token-test/molecule.yml
Labels: backend changes required, team/saturn

#81 tweaks to molecule tests
  molecule/accessible-namespaces-test/molecule.yml
  molecule/config-values-test/converge.yml
  molecule/default/molecule.yml
  molecule/only-view-only-mode-test/molecule.yml
  molecule/os-console-links-test/molecule.yml
  molecule/roles-test/molecule.yml
Labels: team/saturn

#83 increase retries in molecule tests
  molecule/common/prepare-prometheus.yml
  molecule/common/wait_for_kiali_cr_changes.yml
  molecule/common/wait_for_kiali_running.yml
  molecule/default/prepare.yml
Labels: team/saturn

#84 Adapt openid-test scenario to omit expires_in and access_token params
  molecule/openid-test/converge.yml
Labels: team/saturn

#71 enable dependent resource watching
  build/Dockerfile
  deploy/deploy-kiali-operator.sh
  deploy/merge-operator-yaml.sh
  requirements.yml
  roles/default/kiali-deploy/tasks/main.yml
  roles/default/kiali-deploy/tasks/update-status.yml
  watches.yaml
Labels: backend changes required, team/saturn

#90 fix operator due to SDK upgrade
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
  roles/default/kiali-deploy/tasks/create-namespace-label.yml
  roles/default/kiali-deploy/tasks/main.yml
  roles/default/kiali-deploy/tasks/openshift/os-get-kiali-route-url.yml
  roles/default/kiali-deploy/tasks/remove-namespace-label.yml
  roles/default/kiali-remove/tasks/remove-namespace-label.yml
  roles/v1.0/kiali-deploy/tasks/create-namespace-label.yml
  roles/v1.0/kiali-deploy/tasks/main.yml
  roles/v1.0/kiali-deploy/tasks/openshift/os-oauth.yml
  roles/v1.0/kiali-deploy/tasks/remove-namespace-label.yml
  roles/v1.0/kiali-remove/tasks/remove-namespace-label.yml
  roles/v1.12/kiali-deploy/tasks/create-namespace-label.yml
  roles/v1.12/kiali-deploy/tasks/main.yml
  roles/v1.12/kiali-deploy/tasks/openshift/os-get-kiali-route-url.yml
  roles/v1.12/kiali-deploy/tasks/remove-namespace-label.yml
  roles/v1.12/kiali-remove/tasks/remove-namespace-label.yml
Labels: team/saturn

#91 be able to specify where the CR is to be created by the deploy script
  deploy/deploy-kiali-operator.sh
Labels: team/saturn

#93 PoC: add helm chart to install kiali-operator
  .travis.yml
  Makefile
  deploy/charts/kiali-operator/Chart.yaml
  deploy/charts/kiali-operator/crds/crds.yaml
  deploy/charts/kiali-operator/templates/NOTES.txt
  deploy/charts/kiali-operator/templates/_helpers.tpl
  deploy/charts/kiali-operator/templates/clusterrole.yaml
  deploy/charts/kiali-operator/templates/clusterrolebinding.yaml
  deploy/charts/kiali-operator/templates/deployment.yaml
  deploy/charts/kiali-operator/templates/kiali-cr.yaml
  deploy/charts/kiali-operator/templates/serviceaccount.yaml
  deploy/charts/kiali-operator/values.yaml
  deploy/deploy-kiali-operator.sh
  deploy/kiali-operator-all-in-one.yaml
  deploy/merge-operator-yaml.sh
  deploy/namespace.yaml
  deploy/operator.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  docs/index.md
  molecule/accessible-namespaces-test/molecule.yml
  molecule/affinity-tolerations-resources-test/molecule.yml
  molecule/config-values-test/molecule.yml
  molecule/default-namespace-test/molecule.yml
  molecule/default/destroy.yml
  molecule/default/molecule.yml
  molecule/default/prepare.yml
  molecule/docker/Dockerfile
  molecule/metrics-test/molecule.yml
  molecule/null-cr-values-test/molecule.yml
  molecule/only-view-only-mode-test/molecule.yml
  molecule/openid-test/molecule.yml
  molecule/os-console-links-test/molecule.yml
  molecule/roles-test/molecule.yml
  molecule/rolling-restart-test/molecule.yml
  molecule/token-test/molecule.yml
Labels: backend changes required, team/saturn

#103 make sure we only execute helm 3 binary.
  deploy/deploy-kiali-operator.sh
Labels: enhancement, team/saturn

#104 OLM manifest golden copies for v1.22
  manifests/kiali-community/1.22.0/kiali.crd.yaml
  manifests/kiali-community/1.22.0/kiali.monitoringdashboards.crd.yaml
  manifests/kiali-community/1.22.0/kiali.v1.22.0.clusterserviceversion.yaml
  manifests/kiali-community/kiali.package.yaml
  manifests/kiali-upstream/1.22.0/kiali.crd.yaml
  manifests/kiali-upstream/1.22.0/kiali.monitoringdashboards.crd.yaml
  manifests/kiali-upstream/1.22.0/kiali.v1.22.0.clusterserviceversion.yaml
  manifests/kiali-upstream/kiali.package.yaml
Labels: team/saturn
