Repository kiali/kiali-operator, pull requests merged in 2020-08, with the labels that each got.

#105 first attempt at kiali helm chart, for those that refuse to use the operator
  Makefile
  deploy/charts/kiali-server/Chart.yaml
  deploy/charts/kiali-server/crds/crds.yaml
  deploy/charts/kiali-server/templates/NOTES.txt
  deploy/charts/kiali-server/templates/_helpers.tpl
  deploy/charts/kiali-server/templates/cabundle.yaml
  deploy/charts/kiali-server/templates/configmap.yaml
  deploy/charts/kiali-server/templates/dashboards/envoy.yaml
  deploy/charts/kiali-server/templates/dashboards/go.yaml
  deploy/charts/kiali-server/templates/dashboards/kiali.yaml
  deploy/charts/kiali-server/templates/dashboards/micrometer-1.0.6-jvm-pool.yaml
  deploy/charts/kiali-server/templates/dashboards/micrometer-1.0.6-jvm.yaml
  deploy/charts/kiali-server/templates/dashboards/micrometer-1.1-jvm.yaml
  deploy/charts/kiali-server/templates/dashboards/microprofile-1.1.yaml
  deploy/charts/kiali-server/templates/dashboards/microprofile-x.y.yaml
  deploy/charts/kiali-server/templates/dashboards/nodejs.yaml
  deploy/charts/kiali-server/templates/dashboards/quarkus.yaml
  deploy/charts/kiali-server/templates/dashboards/springboot-jvm-pool.yaml
  deploy/charts/kiali-server/templates/dashboards/springboot-jvm.yaml
  deploy/charts/kiali-server/templates/dashboards/springboot-tomcat.yaml
  deploy/charts/kiali-server/templates/dashboards/thorntail.yaml
  deploy/charts/kiali-server/templates/dashboards/tomcat.yaml
  deploy/charts/kiali-server/templates/dashboards/vertx-client.yaml
  deploy/charts/kiali-server/templates/dashboards/vertx-eventbus.yaml
  deploy/charts/kiali-server/templates/dashboards/vertx-jvm.yaml
  deploy/charts/kiali-server/templates/dashboards/vertx-pool.yaml
  deploy/charts/kiali-server/templates/dashboards/vertx-server.yaml
  deploy/charts/kiali-server/templates/deployment.yaml
  deploy/charts/kiali-server/templates/ingess.yaml
  deploy/charts/kiali-server/templates/oauth.yaml
  deploy/charts/kiali-server/templates/role-viewer.yaml
  deploy/charts/kiali-server/templates/role.yaml
  deploy/charts/kiali-server/templates/rolebinding.yaml
  deploy/charts/kiali-server/templates/route.yaml
  deploy/charts/kiali-server/templates/service.yaml
  deploy/charts/kiali-server/templates/serviceaccount.yaml
  deploy/charts/kiali-server/values.yaml
  docs/charts/index.yaml
  docs/charts/kiali-server-v1.23.0-SNAPSHOT.tgz
Labels: enhancement, team/saturn

#106 make client id prefix configurable
  deploy/charts/kiali-server/templates/configmap.yaml
  deploy/charts/kiali-server/templates/oauth.yaml
  deploy/charts/kiali-server/templates/route.yaml
  deploy/charts/kiali-server/values.yaml
  deploy/kiali/kiali_cr.yaml
  roles/default/kiali-deploy/defaults/main.yml
Labels: backend changes required, team/saturn

#107 document how to edit the operator and helm charts
  DEVELOPING.adoc
Labels: documentation, team/saturn

#108 Remove support for the all-in-one yaml generation.
  Makefile
  deploy/kiali-operator-all-in-one.yaml
  deploy/merge-operator-yaml.sh
Labels: backend changes required, team/saturn

#112 changes due to helm repo moving to a separate git repo
  deploy/deploy-kiali-operator.sh
  molecule/asserts/configmap_asserts.yml
  molecule/default/destroy.yml
  molecule/default/prepare.yml
Labels: bug, team/saturn

#115 V1.22 master merge
  .travis.yml
  DEVELOPING.adoc
  Makefile
  deploy/charts/kiali-operator/Chart.yaml
  deploy/charts/kiali-operator/crds/crds.yaml
  deploy/charts/kiali-operator/templates/NOTES.txt
  deploy/charts/kiali-operator/templates/_helpers.tpl
  deploy/charts/kiali-operator/templates/clusterrole.yaml
  deploy/charts/kiali-operator/templates/clusterrolebinding.yaml
  deploy/charts/kiali-operator/templates/deployment.yaml
  deploy/charts/kiali-operator/templates/kiali-cr.yaml
  deploy/charts/kiali-operator/templates/serviceaccount.yaml
  deploy/charts/kiali-operator/values.yaml
  deploy/deploy-kiali-operator.sh
  deploy/kiali-operator-all-in-one.yaml
  deploy/kiali/kiali_cr.yaml
  deploy/merge-operator-yaml.sh
  docs/charts/index.yaml
  docs/charts/kiali-operator-v1.22.0-SNAPSHOT.tgz
  docs/charts/kiali-operator-v1.22.0.tgz
  docs/index.md
  manifests/kiali-community/1.22.0/kiali.crd.yaml
  manifests/kiali-community/1.22.0/kiali.monitoringdashboards.crd.yaml
  manifests/kiali-community/1.22.0/kiali.v1.22.0.clusterserviceversion.yaml
  manifests/kiali-community/kiali.package.yaml
  manifests/kiali-upstream/1.22.0/kiali.crd.yaml
  manifests/kiali-upstream/1.22.0/kiali.monitoringdashboards.crd.yaml
  manifests/kiali-upstream/1.22.0/kiali.v1.22.0.clusterserviceversion.yaml
  manifests/kiali-upstream/kiali.package.yaml
  molecule/asserts/configmap_asserts.yml
  molecule/default/destroy.yml
  molecule/default/prepare.yml
  roles/default/kiali-deploy/defaults/main.yml
  roles/default/kiali-deploy/tasks/main.yml
  roles/default/kiali-deploy/vars/main.yml
Labels: team/saturn

#99 remove login and ldap auth strategies
  deploy/kiali/kiali_cr.yaml
  molecule/null-cr-values-test/converge.yml
  molecule/null-cr-values-test/kiali-cr.yaml
  roles/default/kiali-deploy/defaults/main.yml
  roles/default/kiali-deploy/tasks/main.yml
Labels: team/saturn

#119 Add defaults for API proxy attributes (openid auth)
  deploy/kiali/kiali_cr.yaml
  roles/default/kiali-deploy/defaults/main.yml
Labels: team/saturn
