Repository kiali/kiali-operator, pull requests merged in 2020-11, with the labels that each got.

#182 Fix problem with health_config in operator
  molecule/config-values-test/converge.yml
  roles/default/kiali-deploy/vars/main.yml
  roles/v1.24/kiali-deploy/defaults/main.yml
  roles/v1.24/kiali-deploy/vars/main.yml
Labels: bug

#189 Fix space in defaults/main.yml
  roles/v1.24/kiali-deploy/defaults/main.yml
Labels: backport/v1.24

#183 Fix problem with health_config in operator
  molecule/config-values-test/converge.yml
  roles/default/kiali-deploy/vars/main.yml
  roles/v1.24/kiali-deploy/defaults/main.yml
  roles/v1.24/kiali-deploy/vars/main.yml
Labels: backport/v1.24, bug

#191 fix molecule test so it parses and passes now
  molecule/config-values-test/converge.yml
Labels: team/saturn

#192 update note about molecule-build target
  DEVELOPING.adoc
Labels: team/saturn

#187 Support logger configuration (format, level)
  deploy/kiali/kiali_cr.yaml
  deploy/kiali/kiali_cr_dev.yaml
  deploy/kiali/kiali_cr_dev_servicemesh.yaml
  manifests/README.adoc
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
  molecule/api-test/kiali-cr.yaml
  molecule/null-cr-values-test/converge.yml
  molecule/null-cr-values-test/kiali-cr.yaml
  molecule/openid-test/kiali-cr.yaml
  roles/default/kiali-deploy/defaults/main.yml
  roles/default/kiali-deploy/templates/kubernetes/deployment.yaml
  roles/default/kiali-deploy/templates/openshift/deployment.yaml
Labels: backend changes required, enhancement

#196 update the kiali-ossm CSV description.
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
Labels: backport/v1.24, team/saturn

#197 [v1.24] update the kiali-ossm CSV description.
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
Labels: team/saturn

#195 Remove ComponentStatus from external_services (jaeger, grafana, prom)
  deploy/kiali/kiali_cr.yaml
  molecule/null-cr-values-test/kiali-cr.yaml
  roles/default/kiali-deploy/defaults/main.yml
Labels: backend changes required

#198 Fix molecule tests for NetworkPolicy creation when deploying dev builds inside a Maistra environment
  molecule/api-test/create-simple-mesh.yml
  molecule/default/destroy.yml
  molecule/default/prepare.yml
  molecule/default/process-network-policy.yml
  molecule/metrics-test/converge.yml
Labels: team/saturn

#201 let molecule tests empty prometheus data during testing
  molecule/api-test/converge.yml
  molecule/common/purge-prometheus-data.yml
  molecule/metrics-test/converge.yml
Labels: team/saturn

#203 introduce new olm metadata for upcoming 1.28.0 release
  manifests/kiali-community/1.28.0/kiali.crd.yaml
  manifests/kiali-community/1.28.0/kiali.monitoringdashboards.crd.yaml
  manifests/kiali-community/1.28.0/kiali.v1.28.0.clusterserviceversion.yaml
  manifests/kiali-community/kiali.package.yaml
  manifests/kiali-upstream/1.28.0/kiali.crd.yaml
  manifests/kiali-upstream/1.28.0/kiali.monitoringdashboards.crd.yaml
  manifests/kiali-upstream/1.28.0/kiali.v1.28.0.clusterserviceversion.yaml
  manifests/kiali-upstream/kiali.package.yaml
Labels: team/saturn

#204 Configure kiali-bot to "squash" when merging PRs
  .github/kiali.yml
Labels: team/saturn

#205 Assist in profiling the operator.
  build/Dockerfile
  manifests/kiali-community/1.28.0/kiali.v1.28.0.clusterserviceversion.yaml
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
  manifests/kiali-upstream/1.28.0/kiali.v1.28.0.clusterserviceversion.yaml
Labels: backport/v1.24, team/saturn

#208 [v1.24] disable dependent resource watching
  watches.yaml
Labels: team/saturn

#207 disable dependent resource watching
  watches.yaml
Labels: backport/v1.24, team/saturn

#209 change what the status.accessibleNamespaces field looks like in Kiali CR
  roles/default/kiali-deploy/tasks/main.yml
Labels: backport/v1.24, team/saturn

#210 [v1.24] change what the status.accessibleNamespaces field looks like in Kiali CR
  roles/default/kiali-deploy/tasks/main.yml
Labels: team/saturn
