Repository kiali/kiali-operator, pull requests merged in 2020-12, with the labels that each got.

#211 pass custom helm --set options to deploy script; turn on profiler in molecule via helm
  deploy/deploy-kiali-operator.sh
  molecule/default/prepare.yml
Labels: enhancement, team/saturn

#215 [v1.24] speed up monitoring dashboard creation
  roles/default/kiali-deploy/tasks/main.yml
Labels: team/saturn

#214 speed up monitoring dashboard creation
  roles/default/kiali-deploy/tasks/main.yml
Labels: backport/v1.24

#218 [v1.24] Create a filter plugin to speed up the portion of the ansible script that determines the accessible namespaces
  roles/default/kiali-deploy/filter_plugins/only_accessible_namespaces.py
  roles/default/kiali-deploy/tasks/main.yml
Labels: enhancement, team/saturn

#217 Create a filter plugin to speed up the portion of the ansible script that determines the accessible namespaces
  roles/default/kiali-deploy/filter_plugins/only_accessible_namespaces.py
  roles/default/kiali-deploy/tasks/main.yml
Labels: backport/v1.24, enhancement, team/saturn

#213 [Proxy-config] Add PortForward permissions at pod level
  deploy/kiali/kiali_cr.yaml
  manifests/kiali-community/1.28.0/kiali.v1.28.0.clusterserviceversion.yaml
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
  manifests/kiali-upstream/1.28.0/kiali.v1.28.0.clusterserviceversion.yaml
  roles/default/kiali-deploy/defaults/main.yml
  roles/default/kiali-deploy/templates/kubernetes/role-viewer.yaml
  roles/default/kiali-deploy/templates/kubernetes/role.yaml
  roles/default/kiali-deploy/templates/openshift/role-viewer.yaml
  roles/default/kiali-deploy/templates/openshift/role.yaml
Labels: backend changes required

#216 added container-multi-arch-push-kiali-operator-quay
  Makefile
Labels: team/saturn

#219 clean up this confusing README
  molecule/README.md
Labels: team/saturn

#220 fix molecule image to workaround k8s py library bug
  molecule/docker/Dockerfile
Labels: team/saturn

#224 [v1.24] fix molecule test so it parses and passes now
  molecule/config-values-test/converge.yml
Labels: team/saturn

#225 [v1.24 playbook] Backport to playbook
  roles/v1.24/kiali-deploy/filter_plugins/only_accessible_namespaces.py
  roles/v1.24/kiali-deploy/tasks/main.yml
Labels: backport/v1.24, team/saturn

#226 [v1.24] Backport to v1.24 playbook
  roles/v1.24/kiali-deploy/filter_plugins/only_accessible_namespaces.py
  roles/v1.24/kiali-deploy/tasks/main.yml
Labels: team/saturn

#222 optimize removal of monitoring dashboards
  roles/default/kiali-deploy/tasks/main.yml
  roles/v1.24/kiali-deploy/defaults/main.yml
  roles/v1.24/kiali-deploy/tasks/main.yml
Labels: backport/v1.24, team/saturn

#223 [v1.24] optimize removal of monitoring dashboards
  roles/default/kiali-deploy/tasks/main.yml
  roles/v1.24/kiali-deploy/defaults/main.yml
  roles/v1.24/kiali-deploy/tasks/main.yml
Labels: team/saturn

#227 No need to check for the istiod endpoint at all - assume it is there.
  roles/default/kiali-deploy/tasks/main.yml
  roles/v1.24/kiali-deploy/tasks/main.yml
Labels: backport/v1.24, team/saturn

#228 [v1.24] No need to check for the istiod endpoint at all - assume it is there.
  roles/default/kiali-deploy/tasks/main.yml
  roles/v1.24/kiali-deploy/tasks/main.yml
Labels: team/saturn

#229 get the "run-operator-playbook" make target to behave more like a deployed operator
  DEVELOPING.adoc
  Makefile
  dev-hosts
  dev-playbook-config/README.adoc
  dev-playbook-config/dev-hosts.yaml
  dev-playbook-config/dev-kiali-cr.yaml
  dev-playbook-config/dev-playbook.yaml
  dev-playbook.yml
  molecule/requirements.txt
Labels: team/saturn
