Repository kiali/kiali-operator, pull requests merged in 2021-07, with the labels that each got.

#351 only hide system namespaces that start with "kube-"
  deploy/kiali/kiali_cr.yaml
  roles/default/kiali-deploy/defaults/main.yml
Labels: team/saturn

#348 remove app and version fields from service selector
  roles/default/kiali-deploy/templates/kubernetes/service.yaml
  roles/default/kiali-deploy/templates/openshift/service.yaml
  roles/v1.36/kiali-deploy/templates/kubernetes/service.yaml
  roles/v1.36/kiali-deploy/templates/openshift/service.yaml
Labels: backport/v1.36, bug, team/saturn

#349 [v1.36] remove app and version fields from service selector
  roles/default/kiali-deploy/templates/kubernetes/service.yaml
  roles/default/kiali-deploy/templates/openshift/service.yaml
  roles/v1.36/kiali-deploy/templates/kubernetes/service.yaml
  roles/v1.36/kiali-deploy/templates/openshift/service.yaml
Labels: bug, team/saturn

#350 ensure the label value is quoted in case the user wants to set this as a boolean
  roles/default/kiali-deploy/tasks/main.yml
Labels: bug, team/saturn

#353 operator installmodes - only support AllNamespaces
  manifests/kiali-community/1.37.0/manifests/kiali.v1.37.0.clusterserviceversion.yaml
  manifests/kiali-upstream/1.37.0/manifests/kiali.v1.37.0.clusterserviceversion.yaml
Labels: team/saturn

#352 molecule test for the new dashboard annotations
  molecule/api-test/cleanup.yml
  molecule/api-test/create-simple-mesh.yml
  molecule/api-test/dashboards.test.yaml
  molecule/api-test/delete-simple-mesh.yml
Labels: area/testing, team/saturn

#356 [v1.36] molecule test for the new dashboard annotations (#352)
  molecule/api-test/cleanup.yml
  molecule/api-test/create-simple-mesh.yml
  molecule/api-test/dashboards.test.yaml
  molecule/api-test/delete-simple-mesh.yml
Labels: area/testing, team/saturn

#358 new v1.38.0 OLM manifests
  manifests/kiali-community/1.38.0/bundle.Dockerfile
  manifests/kiali-community/1.38.0/manifests/kiali.crd.yaml
  manifests/kiali-community/1.38.0/manifests/kiali.v1.38.0.clusterserviceversion.yaml
  manifests/kiali-community/1.38.0/metadata/annotations.yaml
  manifests/kiali-upstream/1.38.0/bundle.Dockerfile
  manifests/kiali-upstream/1.38.0/manifests/kiali.crd.yaml
  manifests/kiali-upstream/1.38.0/manifests/kiali.v1.38.0.clusterserviceversion.yaml
  manifests/kiali-upstream/1.38.0/metadata/annotations.yaml
Labels: team/saturn

#357 Adding Jaeger (internal) integration basic test
  molecule/default/prepare.yml
  molecule/jaeger-test/converge.yml
  molecule/jaeger-test/kiali-cr.yaml
  molecule/jaeger-test/molecule.yml
  molecule/jaeger-test/update-jaeger-url.yml
Labels: area/testing, backport/v1.36

#359 don't look at tracing settings - molecule framework overrides it if on service mesh
  molecule/null-cr-values-test/converge.yml
Labels: area/testing, backport/v1.36, team/saturn

#360 [v1.36] Jaeger integration molecule test
  molecule/default/prepare.yml
  molecule/jaeger-test/converge.yml
  molecule/jaeger-test/kiali-cr.yaml
  molecule/jaeger-test/molecule.yml
  molecule/jaeger-test/update-jaeger-url.yml
  molecule/null-cr-values-test/converge.yml
Labels: area/testing

#361 fix molecule tests to pass when running with OSSM
  molecule/api-test/create-simple-mesh.yml
  molecule/common/tasks.yml
  molecule/metrics-test/converge.yml
Labels: area/testing, backport/v1.36, team/saturn

#364 CSV metadata annotation value should be all lowercase
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
Labels: team/saturn

#362 [v1.36] fix molecule tests to pass when running with OSSM
  molecule/api-test/create-simple-mesh.yml
  molecule/common/tasks.yml
  molecule/metrics-test/converge.yml
Labels: area/testing, team/saturn

#342 Add ui default support for graph traffic rates
  deploy/kiali/kiali_cr.yaml
  roles/default/kiali-deploy/defaults/main.yml
Labels: backend changes required, team/saturn

#366 test token auth strategy session timeout
  molecule/token-test/converge.yml
  molecule/token-test/kiali-cr.yaml
  molecule/token-test/molecule.yml
Labels: area/testing, backport/v1.36, team/saturn

#367 test token auth strategy session timeout
  molecule/token-test/converge.yml
  molecule/token-test/kiali-cr.yaml
  molecule/token-test/molecule.yml
Labels: area/testing, team/saturn

#368 [v1.36] make value all lowercase in olm metadata
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
Labels: team/saturn

#371 [molecule] wait for the kiali CRD to be established
  molecule/default/prepare.yml
Labels: area/testing

#372 [v1.36][molecule] wait for the kiali CRD to be established (#371)
  molecule/default/prepare.yml
Labels: area/testing, team/saturn

#374 sort, and show defaults properly
  deploy/kiali/kiali_cr.yaml
Labels: backport/v1.36, team/saturn

#373 [v1.36] sort settings
  deploy/kiali/kiali_cr.yaml
Labels: team/saturn

#330 Bump up to 4.8 operator SDK.
  DEVELOPING.adoc
  Makefile
  requirements.yml
  roles/default/kiali-deploy/tasks/kubernetes/k8s-main.yml
  roles/default/kiali-deploy/tasks/main.yml
  roles/default/kiali-deploy/tasks/openshift/os-main.yml
  roles/default/kiali-deploy/tasks/remove-clusterroles.yml
  roles/default/kiali-deploy/templates/kubernetes/ingress.yaml
  roles/default/kiali-deploy/templates/kubernetes/service.yaml
  roles/default/kiali-deploy/templates/openshift/service.yaml
  roles/default/kiali-remove/tasks/main.yml
  roles/default/kiali-remove/tasks/remove-clusterroles.yml
  roles/v1.36/kiali-deploy/tasks/kubernetes/k8s-main.yml
  roles/v1.36/kiali-deploy/tasks/main.yml
  roles/v1.36/kiali-deploy/tasks/openshift/os-main.yml
  roles/v1.36/kiali-deploy/tasks/remove-clusterroles.yml
  roles/v1.36/kiali-deploy/templates/kubernetes/ingress.yaml
  roles/v1.36/kiali-deploy/templates/kubernetes/service.yaml
  roles/v1.36/kiali-deploy/templates/openshift/service.yaml
  roles/v1.36/kiali-remove/tasks/main.yml
  roles/v1.36/kiali-remove/tasks/remove-clusterroles.yml
Labels: backport/v1.36, team/saturn

#375 [v1.36] Bump up to 4.8 operator SDK.
  DEVELOPING.adoc
  Makefile
  requirements.yml
  roles/default/kiali-deploy/tasks/kubernetes/k8s-main.yml
  roles/default/kiali-deploy/tasks/main.yml
  roles/default/kiali-deploy/tasks/openshift/os-main.yml
  roles/default/kiali-deploy/tasks/remove-clusterroles.yml
  roles/default/kiali-deploy/templates/kubernetes/ingress.yaml
  roles/default/kiali-deploy/templates/kubernetes/service.yaml
  roles/default/kiali-deploy/templates/openshift/service.yaml
  roles/default/kiali-remove/tasks/main.yml
  roles/default/kiali-remove/tasks/remove-clusterroles.yml
  roles/v1.36/kiali-deploy/tasks/kubernetes/k8s-main.yml
  roles/v1.36/kiali-deploy/tasks/main.yml
  roles/v1.36/kiali-deploy/tasks/openshift/os-main.yml
  roles/v1.36/kiali-deploy/tasks/remove-clusterroles.yml
  roles/v1.36/kiali-deploy/templates/kubernetes/ingress.yaml
  roles/v1.36/kiali-deploy/templates/kubernetes/service.yaml
  roles/v1.36/kiali-deploy/templates/openshift/service.yaml
  roles/v1.36/kiali-remove/tasks/main.yml
  roles/v1.36/kiali-remove/tasks/remove-clusterroles.yml
Labels: team/saturn

#376 turn on at least debug level on all molecule tests. auth related tests are at trace
  molecule/accessible-namespaces-test/kiali-cr.yaml
  molecule/affinity-tolerations-resources-test/kiali-cr.yaml
  molecule/api-test/kiali-cr.yaml
  molecule/config-values-test/kiali-cr.yaml
  molecule/default-namespace-test/kiali-cr.yaml
  molecule/header-auth-test/kiali-cr.yaml
  molecule/instance-name-test/kiali-cr.yaml
  molecule/jaeger-test/kiali-cr.yaml
  molecule/kiali-cr.yaml
  molecule/metrics-test/kiali-cr.yaml
  molecule/only-view-only-mode-test/kiali-cr.yaml
  molecule/openid-test/kiali-cr.yaml
  molecule/openshift-auth-test/kiali-cr.yaml
  molecule/os-console-links-test/kiali-cr.yaml
  molecule/rolling-restart-test/kiali-cr.yaml
  molecule/token-test/kiali-cr.yaml
Labels: area/testing, backport/v1.36
