Repository kiali/kiali-operator, pull requests merged in 2021-04, with the labels that each got.

#276 Fix comment in sample Kiali CR
  deploy/kiali/kiali_cr.yaml
Labels: team/saturn

#280 by default, don't allow ad-hoc namespaces
  manifests/kiali-community/1.33.0/kiali.v1.33.0.clusterserviceversion.yaml
  manifests/kiali-upstream/1.33.0/kiali.v1.33.0.clusterserviceversion.yaml
  roles/v1.12/kiali-deploy/tasks/main.yml
  roles/v1.24/kiali-deploy/tasks/main.yml
Labels: enhancement, team/saturn

#279 be able to specify CR spec.version to test
  molecule/accessible-namespaces-test/kiali-cr.yaml
  molecule/accessible-namespaces-test/molecule.yml
  molecule/affinity-tolerations-resources-test/kiali-cr.yaml
  molecule/affinity-tolerations-resources-test/molecule.yml
  molecule/api-test/kiali-cr.yaml
  molecule/api-test/molecule.yml
  molecule/config-values-test/kiali-cr.yaml
  molecule/config-values-test/molecule.yml
  molecule/default-namespace-test/kiali-cr.yaml
  molecule/default-namespace-test/molecule.yml
  molecule/default/molecule.yml
  molecule/header-auth-test/kiali-cr.yaml
  molecule/header-auth-test/molecule.yml
  molecule/kiali-cr.yaml
  molecule/metrics-test/kiali-cr.yaml
  molecule/metrics-test/molecule.yml
  molecule/null-cr-values-test/kiali-cr.yaml
  molecule/null-cr-values-test/molecule.yml
  molecule/only-view-only-mode-test/kiali-cr.yaml
  molecule/only-view-only-mode-test/molecule.yml
  molecule/openid-test/kiali-cr.yaml
  molecule/openid-test/molecule.yml
  molecule/openshift-auth-test/kiali-cr.yaml
  molecule/openshift-auth-test/molecule.yml
  molecule/os-console-links-test/kiali-cr.yaml
  molecule/os-console-links-test/molecule.yml
  molecule/roles-test/molecule.yml
  molecule/rolling-restart-test/kiali-cr.yaml
  molecule/rolling-restart-test/molecule.yml
  molecule/token-test/molecule.yml
Labels: backend changes required, team/saturn

#282 Remove support for v1.0
  deploy/kiali/kiali_cr.yaml
  playbooks/default-supported-images.yml
  roles/v1.0/kiali-deploy/defaults/main.yml
  roles/v1.0/kiali-deploy/meta/main.yml
  roles/v1.0/kiali-deploy/tasks/create-namespace-label.yml
  roles/v1.0/kiali-deploy/tasks/kubernetes/k8s-main.yml
  roles/v1.0/kiali-deploy/tasks/main.yml
  roles/v1.0/kiali-deploy/tasks/openshift/os-main.yml
  roles/v1.0/kiali-deploy/tasks/openshift/os-oauth.yml
  roles/v1.0/kiali-deploy/tasks/process-additional-roles.yml
  roles/v1.0/kiali-deploy/tasks/process-resource.yml
  roles/v1.0/kiali-deploy/tasks/remove-clusterroles.yml
  roles/v1.0/kiali-deploy/tasks/remove-namespace-label.yml
  roles/v1.0/kiali-deploy/tasks/remove-roles.yml
  roles/v1.0/kiali-deploy/templates/dashboards/go.yaml
  roles/v1.0/kiali-deploy/templates/dashboards/kiali.yaml
  roles/v1.0/kiali-deploy/templates/dashboards/micrometer-1.0.6-jvm-pool.yaml
  roles/v1.0/kiali-deploy/templates/dashboards/micrometer-1.0.6-jvm.yaml
  roles/v1.0/kiali-deploy/templates/dashboards/micrometer-1.1-jvm.yaml
  roles/v1.0/kiali-deploy/templates/dashboards/microprofile-1.1.yaml
  roles/v1.0/kiali-deploy/templates/dashboards/microprofile-x.y.yaml
  roles/v1.0/kiali-deploy/templates/dashboards/nodejs.yaml
  roles/v1.0/kiali-deploy/templates/dashboards/quarkus.yaml
  roles/v1.0/kiali-deploy/templates/dashboards/springboot-jvm-pool.yaml
  roles/v1.0/kiali-deploy/templates/dashboards/springboot-jvm.yaml
  roles/v1.0/kiali-deploy/templates/dashboards/springboot-tomcat.yaml
  roles/v1.0/kiali-deploy/templates/dashboards/thorntail.yaml
  roles/v1.0/kiali-deploy/templates/dashboards/tomcat.yaml
  roles/v1.0/kiali-deploy/templates/dashboards/vertx-client.yaml
  roles/v1.0/kiali-deploy/templates/dashboards/vertx-eventbus.yaml
  roles/v1.0/kiali-deploy/templates/dashboards/vertx-jvm.yaml
  roles/v1.0/kiali-deploy/templates/dashboards/vertx-pool.yaml
  roles/v1.0/kiali-deploy/templates/dashboards/vertx-server.yaml
  roles/v1.0/kiali-deploy/templates/kubernetes/configmap.yaml
  roles/v1.0/kiali-deploy/templates/kubernetes/deployment.yaml
  roles/v1.0/kiali-deploy/templates/kubernetes/ingress.yaml
  roles/v1.0/kiali-deploy/templates/kubernetes/role-viewer.yaml
  roles/v1.0/kiali-deploy/templates/kubernetes/role.yaml
  roles/v1.0/kiali-deploy/templates/kubernetes/rolebinding.yaml
  roles/v1.0/kiali-deploy/templates/kubernetes/service.yaml
  roles/v1.0/kiali-deploy/templates/kubernetes/serviceaccount.yaml
  roles/v1.0/kiali-deploy/templates/openshift/cabundle.yaml
  roles/v1.0/kiali-deploy/templates/openshift/configmap.yaml
  roles/v1.0/kiali-deploy/templates/openshift/deployment.yaml
  roles/v1.0/kiali-deploy/templates/openshift/oauth.yaml
  roles/v1.0/kiali-deploy/templates/openshift/role-viewer.yaml
  roles/v1.0/kiali-deploy/templates/openshift/role.yaml
  roles/v1.0/kiali-deploy/templates/openshift/rolebinding.yaml
  roles/v1.0/kiali-deploy/templates/openshift/route.yaml
  roles/v1.0/kiali-deploy/templates/openshift/service.yaml
  roles/v1.0/kiali-deploy/templates/openshift/serviceaccount.yaml
  roles/v1.0/kiali-deploy/vars/main.yml
  roles/v1.0/kiali-remove/defaults/main.yml
  roles/v1.0/kiali-remove/tasks/main.yml
  roles/v1.0/kiali-remove/tasks/remove-clusterroles.yml
  roles/v1.0/kiali-remove/tasks/remove-namespace-label.yml
  roles/v1.0/kiali-remove/tasks/remove-roles.yml
  roles/v1.0/kiali-remove/vars/main.yml
Labels: team/saturn

#285 update kiali-cr docs to indicate auto-generation of certs no longer happens on non-OpenShift envs.
  deploy/kiali/kiali_cr.yaml
Labels: team/saturn

#284 Be able to disable ad hoc images.
  manifests/kiali-community/1.33.0/kiali.v1.33.0.clusterserviceversion.yaml
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
  manifests/kiali-upstream/1.33.0/kiali.v1.33.0.clusterserviceversion.yaml
  molecule/default/prepare.yml
  roles/default/kiali-deploy/tasks/main.yml
  roles/v1.12/kiali-deploy/tasks/main.yml
  roles/v1.24/kiali-deploy/tasks/main.yml
Labels: team/saturn

#288 Remove HPA permissions
  manifests/kiali-community/1.33.0/kiali.v1.33.0.clusterserviceversion.yaml
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
  manifests/kiali-upstream/1.33.0/kiali.v1.33.0.clusterserviceversion.yaml
  roles/default/kiali-deploy/templates/kubernetes/role-viewer.yaml
  roles/default/kiali-deploy/templates/kubernetes/role.yaml
  roles/default/kiali-deploy/templates/openshift/role-viewer.yaml
  roles/default/kiali-deploy/templates/openshift/role.yaml
  roles/v1.12/kiali-deploy/templates/kubernetes/role-viewer.yaml
  roles/v1.12/kiali-deploy/templates/kubernetes/role.yaml
  roles/v1.12/kiali-deploy/templates/openshift/role-viewer.yaml
  roles/v1.12/kiali-deploy/templates/openshift/role.yaml
  roles/v1.24/kiali-deploy/templates/kubernetes/role-viewer.yaml
  roles/v1.24/kiali-deploy/templates/kubernetes/role.yaml
  roles/v1.24/kiali-deploy/templates/openshift/role-viewer.yaml
  roles/v1.24/kiali-deploy/templates/openshift/role.yaml
Labels: backend changes required

#283 [molecule] support for existing operator that does not allow for ad-hoc kiali namespace
  molecule/accessible-namespaces-test/molecule.yml
  molecule/affinity-tolerations-resources-test/molecule.yml
  molecule/api-test/molecule.yml
  molecule/config-values-test/molecule.yml
  molecule/default-namespace-test/molecule.yml
  molecule/default/molecule.yml
  molecule/header-auth-test/molecule.yml
  molecule/metrics-test/molecule.yml
  molecule/null-cr-values-test/molecule.yml
  molecule/only-view-only-mode-test/molecule.yml
  molecule/openid-test/molecule.yml
  molecule/openshift-auth-test/molecule.yml
  molecule/os-console-links-test/molecule.yml
  molecule/roles-test/molecule.yml
  molecule/rolling-restart-test/molecule.yml
  molecule/token-test/molecule.yml
Labels: team/saturn

#289 Add new settings required to support Azure
  deploy/kiali/kiali_cr.yaml
  roles/default/kiali-deploy/defaults/main.yml
  roles/default/kiali-deploy/tasks/main.yml
Labels: team/saturn

#287 audit permissions
  manifests/kiali-community/1.33.0/kiali.v1.33.0.clusterserviceversion.yaml
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
  manifests/kiali-upstream/1.33.0/kiali.v1.33.0.clusterserviceversion.yaml
  roles/default/kiali-deploy/templates/kubernetes/role-controlplane.yaml
  roles/default/kiali-deploy/templates/kubernetes/role-viewer.yaml
  roles/default/kiali-deploy/templates/kubernetes/role.yaml
  roles/default/kiali-deploy/templates/openshift/role-controlplane.yaml
  roles/default/kiali-deploy/templates/openshift/role-viewer.yaml
  roles/default/kiali-deploy/templates/openshift/role.yaml
  roles/v1.12/kiali-deploy/templates/kubernetes/role-viewer.yaml
  roles/v1.12/kiali-deploy/templates/kubernetes/role.yaml
  roles/v1.12/kiali-deploy/templates/openshift/role-viewer.yaml
  roles/v1.12/kiali-deploy/templates/openshift/role.yaml
  roles/v1.24/kiali-deploy/templates/kubernetes/role-viewer.yaml
  roles/v1.24/kiali-deploy/templates/kubernetes/role.yaml
  roles/v1.24/kiali-deploy/templates/openshift/role-viewer.yaml
  roles/v1.24/kiali-deploy/templates/openshift/role.yaml
Labels: team/saturn

#294 operator should be looking for crd v1 now
  roles/default/kiali-deploy/tasks/main.yml
Labels: bug, team/saturn

#296 new 1.34.0 manifests
  manifests/kiali-community/1.34.0/kiali.crd.yaml
  manifests/kiali-community/1.34.0/kiali.monitoringdashboards.crd.yaml
  manifests/kiali-community/1.34.0/kiali.v1.34.0.clusterserviceversion.yaml
  manifests/kiali-community/kiali.package.yaml
  manifests/kiali-upstream/1.34.0/kiali.crd.yaml
  manifests/kiali-upstream/1.34.0/kiali.monitoringdashboards.crd.yaml
  manifests/kiali-upstream/1.34.0/kiali.v1.34.0.clusterserviceversion.yaml
  manifests/kiali-upstream/kiali.package.yaml
Labels: team/saturn

#293 make the operator go faster
  DEVELOPING.adoc
  manifests/kiali-community/1.34.0/kiali.v1.34.0.clusterserviceversion.yaml
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
  manifests/kiali-upstream/1.34.0/kiali.v1.34.0.clusterserviceversion.yaml
  molecule/accessible-namespaces-test/converge.yml
  roles/default/kiali-deploy/filter_plugins/only_accessible_namespaces.py
  roles/default/kiali-deploy/tasks/create-namespace-label.yml
  roles/default/kiali-deploy/tasks/kubernetes/k8s-main.yml
  roles/default/kiali-deploy/tasks/main.yml
  roles/default/kiali-deploy/tasks/openshift/os-main.yml
  roles/default/kiali-deploy/tasks/process-additional-roles.yml
  roles/default/kiali-deploy/tasks/remove-namespace-label.yml
  roles/default/kiali-deploy/tasks/remove-roles.yml
  roles/default/kiali-deploy/tasks/update-status-progress.yml
  roles/default/kiali-deploy/tasks/update-status.yml
  roles/default/kiali-deploy/templates/kubernetes/role-viewer.yaml
  roles/default/kiali-deploy/templates/kubernetes/role.yaml
  roles/default/kiali-deploy/templates/kubernetes/rolebinding.yaml
  roles/default/kiali-deploy/templates/openshift/console-links.yaml
  roles/default/kiali-deploy/templates/openshift/role-viewer.yaml
  roles/default/kiali-deploy/templates/openshift/role.yaml
  roles/default/kiali-deploy/templates/openshift/rolebinding.yaml
  roles/default/kiali-remove/defaults/main.yml
  roles/default/kiali-remove/tasks/main.yml
  roles/default/kiali-remove/tasks/remove-clusterroles.yml
  roles/default/kiali-remove/tasks/remove-namespace-label.yml
  roles/default/kiali-remove/tasks/remove-roles.yml
  roles/default/kiali-remove/vars/main.yml
Labels: do not merge, team/saturn

#301 remove 1.0 image support, add new 1.33 image support.
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
Labels: team/saturn

#302 [v1.33] remove 1.0 image support, add new 1.33 image support.
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
Labels: team/saturn

#304 [v1.33] fix metadata - image name is rhel8 not rhel7
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
Labels: team/saturn

#305 fix metadata - image name is rhel8 not rhel7
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
Labels: team/saturn

#306 go back to defaulting to the same kiali image version as that of the operator
  playbooks/default-supported-images.yml
Labels: team/saturn

#298 Add host stanza to Ingress
  roles/default/kiali-deploy/templates/kubernetes/ingress.yaml
Labels: helm charts changes required, team/saturn
