Repository kiali/kiali-operator, pull requests merged in 2021-08, with the labels that each got.

#307 add true can-i check to make sure the operator has the permissions it needs
  manifests/kiali-community/1.38.0/manifests/kiali.v1.38.0.clusterserviceversion.yaml
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
  manifests/kiali-upstream/1.38.0/manifests/kiali.v1.38.0.clusterserviceversion.yaml
  roles/default/kiali-deploy/tasks/main.yml
Labels: helm charts changes required, team/saturn

#380 Grafana integration test
  molecule/default/prepare.yml
  molecule/grafana-test/converge.yml
  molecule/grafana-test/kiali-cr.yaml
  molecule/grafana-test/molecule.yml
Labels: area/testing

#384 use_grpc by default. health_check_url removal from tracing
  deploy/kiali/kiali_cr.yaml
  roles/default/kiali-deploy/defaults/main.yml
Labels: bug

#385 change default in kiali_cr.yaml comment
  deploy/kiali/kiali_cr.yaml
Labels: team/saturn

#387 [v1.38] backport fix for the jaeger config
  deploy/kiali/kiali_cr.yaml
  roles/default/kiali-deploy/defaults/main.yml
Labels: team/saturn

#388 document how to use pod_labels to inject sidecar
  deploy/kiali/kiali_cr.yaml
Labels: team/saturn

#381 conform to the correct route syntax for target port
  roles/default/kiali-deploy/templates/openshift/route.yaml
  roles/v1.36/kiali-deploy/templates/openshift/route.yaml
Labels: backport/v1.36, team/saturn

#382 [v1.36] conform to the correct route syntax for target port
  roles/default/kiali-deploy/templates/openshift/route.yaml
  roles/v1.36/kiali-deploy/templates/openshift/route.yaml
Labels: team/saturn

#386 [v1.36] Grafana integration test (#380)
  molecule/default/prepare.yml
  molecule/grafana-test/converge.yml
  molecule/grafana-test/kiali-cr.yaml
  molecule/grafana-test/molecule.yml
Labels: area/testing, team/saturn

#390 allow user to be able to set grafana in_cluster_url to empty string
  deploy/kiali/kiali_cr.yaml
  roles/default/kiali-deploy/defaults/main.yml
  roles/default/kiali-deploy/tasks/main.yml
Labels: team/saturn

#392 bump the manifest metadata to match the latest 1.38 version (which is now 1.38.1)
  manifests/kiali-community/1.38.1/bundle.Dockerfile
  manifests/kiali-community/1.38.1/manifests/kiali.crd.yaml
  manifests/kiali-community/1.38.1/manifests/kiali.v1.38.1.clusterserviceversion.yaml
  manifests/kiali-community/1.38.1/metadata/annotations.yaml
  manifests/kiali-upstream/1.38.1/bundle.Dockerfile
  manifests/kiali-upstream/1.38.1/manifests/kiali.crd.yaml
  manifests/kiali-upstream/1.38.1/manifests/kiali.v1.38.1.clusterserviceversion.yaml
  manifests/kiali-upstream/1.38.1/metadata/annotations.yaml
Labels: team/saturn

#393 introduce 1.39.0 OLM manifests
  manifests/kiali-community/1.39.0/bundle.Dockerfile
  manifests/kiali-community/1.39.0/manifests/kiali.crd.yaml
  manifests/kiali-community/1.39.0/manifests/kiali.v1.39.0.clusterserviceversion.yaml
  manifests/kiali-community/1.39.0/metadata/annotations.yaml
  manifests/kiali-upstream/1.39.0/bundle.Dockerfile
  manifests/kiali-upstream/1.39.0/manifests/kiali.crd.yaml
  manifests/kiali-upstream/1.39.0/manifests/kiali.v1.39.0.clusterserviceversion.yaml
  manifests/kiali-upstream/1.39.0/metadata/annotations.yaml
Labels: team/saturn

#394 update DEVELOPING checklist to include how to update control-plane-only roles
  DEVELOPING.adoc
Labels: team/saturn

#396 [molecule] set istio config when running in maistra environment
  molecule/asserts/configmap_asserts.yml
  molecule/default/prepare.yml
Labels: team/saturn, area/testing, backport/v1.36

#397 [v1.36][molecule] set istio config when running in maistra environment
  molecule/asserts/configmap_asserts.yml
  molecule/default/prepare.yml
Labels: team/saturn, area/testing

#398 [molecule] when setting the health check url, just set it to the known good url
  molecule/grafana-test/converge.yml
Labels: team/saturn, area/testing, backport/v1.36

#399 [v1.36] [molecule] when setting the health-check-url, just set it to the known good url
  molecule/grafana-test/converge.yml
Labels: team/saturn, area/testing

#401 trivial - fix help text in prepare-community-prs script
  manifests/prepare-community-prs.sh
Labels: team/saturn

#402 1.40.0 versions of OLM metadata
  manifests/kiali-community/1.40.0/bundle.Dockerfile
  manifests/kiali-community/1.40.0/manifests/kiali.crd.yaml
  manifests/kiali-community/1.40.0/manifests/kiali.v1.40.0.clusterserviceversion.yaml
  manifests/kiali-community/1.40.0/metadata/annotations.yaml
  manifests/kiali-upstream/1.40.0/bundle.Dockerfile
  manifests/kiali-upstream/1.40.0/manifests/kiali.crd.yaml
  manifests/kiali-upstream/1.40.0/manifests/kiali.v1.40.0.clusterserviceversion.yaml
  manifests/kiali-upstream/1.40.0/metadata/annotations.yaml
Labels: team/saturn

#403 operator does not need perms for event and pvc resources
  manifests/kiali-community/1.40.0/manifests/kiali.v1.40.0.clusterserviceversion.yaml
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
  manifests/kiali-upstream/1.40.0/manifests/kiali.v1.40.0.clusterserviceversion.yaml
Labels: enhancement, backport/v1.36
