Repository kiali/kiali-operator, pull requests merged in 2021-05, with the labels that each got.

#309 [v1.24] no longer support 1.0.x kiali servers; revert CRDs back to v1beta1
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
  manifests/kiali-ossm/manifests/kiali.crd.yaml
  manifests/kiali-ossm/manifests/kiali.monitoringdashboards.crd.yaml
Labels: team/saturn

#310 fix molecule test - make the resource limits more realistic
  molecule/affinity-tolerations-resources-test/converge.yml
Labels: area/testing, team/saturn

#312 update molecule
  molecule/docker/Dockerfile
  molecule/requirements.txt
Labels: area/testing, team/saturn

#314 Add component_status.is_proxy flag
  deploy/kiali/kiali_cr.yaml
  roles/default/kiali-deploy/defaults/main.yml
Labels: team/saturn

#317 new metadata for 1.35.0
  manifests/kiali-community/1.35.0/kiali.crd.yaml
  manifests/kiali-community/1.35.0/kiali.monitoringdashboards.crd.yaml
  manifests/kiali-community/1.35.0/kiali.v1.35.0.clusterserviceversion.yaml
  manifests/kiali-community/kiali.package.yaml
  manifests/kiali-upstream/1.35.0/kiali.crd.yaml
  manifests/kiali-upstream/1.35.0/kiali.monitoringdashboards.crd.yaml
  manifests/kiali-upstream/1.35.0/kiali.v1.35.0.clusterserviceversion.yaml
  manifests/kiali-upstream/kiali.package.yaml
Labels: team/saturn

#316 more security to the kiali pod
  roles/default/kiali-deploy/templates/kubernetes/deployment.yaml
  roles/default/kiali-deploy/templates/openshift/deployment.yaml
Labels: enhancement, team/saturn

#318 add security to operator pod
  manifests/kiali-community/1.35.0/kiali.v1.35.0.clusterserviceversion.yaml
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
  manifests/kiali-upstream/1.35.0/kiali.v1.35.0.clusterserviceversion.yaml
Labels: team/saturn

#320 add status.environment so we can see what the operator thinks is its env is; remove superflous check
  roles/default/kiali-deploy/tasks/main.yml
Labels: team/saturn

#322 [operator][molecule] increase wait timeout when deleting resource
  molecule/instance-name-test/converge.yml
Labels: team/saturn

#315 Introduce Graph Find/Hide presets
  deploy/kiali/kiali_cr.yaml
  roles/default/kiali-deploy/defaults/main.yml
Labels: backend changes required, team/saturn

#324 olm metadata for v1.36.0
  manifests/kiali-community/1.36.0/kiali.crd.yaml
  manifests/kiali-community/1.36.0/kiali.monitoringdashboards.crd.yaml
  manifests/kiali-community/1.36.0/kiali.v1.36.0.clusterserviceversion.yaml
  manifests/kiali-community/kiali.package.yaml
  manifests/kiali-upstream/1.36.0/kiali.crd.yaml
  manifests/kiali-upstream/1.36.0/kiali.monitoringdashboards.crd.yaml
  manifests/kiali-upstream/1.36.0/kiali.v1.36.0.clusterserviceversion.yaml
  manifests/kiali-upstream/kiali.package.yaml
Labels: team/saturn
