Repository kiali/kiali-operator, pull requests merged in 2021-11, with the labels that each got.

#441 Add root namespace property into Kiali config map
  deploy/kiali/kiali_cr.yaml
  molecule/asserts/configmap_asserts.yml
  roles/default/kiali-deploy/defaults/main.yml
  roles/default/kiali-deploy/tasks/main.yml
Labels: requires server PR

#445 explicitly enable ingress in all molecule tests
  molecule/accessible-namespaces-test/kiali-cr.yaml
  molecule/affinity-tolerations-resources-test/kiali-cr.yaml
  molecule/api-test/kiali-cr.yaml
  molecule/config-values-test/kiali-cr.yaml
  molecule/default-namespace-test/kiali-cr.yaml
  molecule/grafana-test/kiali-cr.yaml
  molecule/header-auth-test/kiali-cr.yaml
  molecule/instance-name-test/kiali-cr.yaml
  molecule/jaeger-test/kiali-cr.yaml
  molecule/kiali-cr.yaml
  molecule/metrics-test/kiali-cr.yaml
  molecule/null-cr-values-test/converge.yml
  molecule/null-cr-values-test/kiali-cr.yaml
  molecule/only-view-only-mode-test/kiali-cr.yaml
  molecule/openid-test/kiali-cr.yaml
  molecule/openshift-auth-test/kiali-cr.yaml
  molecule/os-console-links-test/kiali-cr.yaml
  molecule/read-certs-secrets-test/kiali-cr.yaml
  molecule/rolling-restart-test/kiali-cr.yaml
  molecule/token-test/kiali-cr.yaml
Labels: area/testing

#451 fix 1.36 playbook to only hide kube- namespaces (not kube*)
  roles/v1.36/kiali-deploy/defaults/main.yml
Labels: backport/v1.36

#449 implement some best practices
  deploy/kiali/kiali_cr.yaml
  manifests/kiali-community/1.44.0/manifests/kiali.v1.44.0.clusterserviceversion.yaml
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
  manifests/kiali-upstream/1.44.0/manifests/kiali.v1.44.0.clusterserviceversion.yaml
  molecule/config-values-test/converge.yml
  molecule/null-cr-values-test/converge.yml
  roles/default/kiali-deploy/defaults/main.yml
  roles/default/kiali-deploy/tasks/main.yml
  roles/default/kiali-deploy/templates/kubernetes/ingress.yaml
  roles/default/kiali-deploy/templates/openshift/route.yaml
  roles/v1.36/kiali-deploy/defaults/main.yml
  roles/v1.36/kiali-deploy/tasks/main.yml
  roles/v1.36/kiali-deploy/templates/kubernetes/ingress.yaml
  roles/v1.36/kiali-deploy/templates/openshift/route.yaml
Labels: backport/v1.36
