Repository kiali/kiali-operator, pull requests merged in 2021-01, with the labels that each got.

#232 fix operator on ARM64 by bumping operator sdk
  Makefile
  build/Dockerfile
Labels: team/saturn

#233 Create Jenkins pipeline to release the operator
  Jenkinsfile
Labels: team/saturn

#235 Add permissions needed for the "Mesh" page
  roles/default/kiali-deploy/tasks/kubernetes/k8s-main.yml
  roles/default/kiali-deploy/tasks/openshift/os-main.yml
  roles/default/kiali-deploy/templates/kubernetes/role-controlplane.yaml
  roles/default/kiali-deploy/templates/kubernetes/rolebinding-controlplane.yaml
  roles/default/kiali-deploy/templates/openshift/role-controlplane.yaml
  roles/default/kiali-deploy/templates/openshift/rolebinding-controlplane.yaml
  roles/default/kiali-remove/tasks/remove-clusterroles.yml
Labels: team/saturn

#236 Updated labels to support amd64, s390z and ppc64le
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
Labels: backport/v1.24, team/saturn

#239 openshift-auth-test molecule test
  molecule/openshift-auth-test/converge.yml
  molecule/openshift-auth-test/kiali-cr.yaml
  molecule/openshift-auth-test/molecule.yml
Labels: backend changes required, team/saturn
