Repository kiali/kiali-operator, pull requests merged in 2021-10, with the labels that each got.

#427 Kiali Istio dashboards incompatible with thanos-query
  deploy/kiali/kiali_cr.yaml
  roles/default/kiali-deploy/defaults/main.yml
Labels: requires server PR

#432 implemented hostaliases setting;
  deploy/kiali/kiali_cr.yaml
  molecule/config-values-test/converge.yml
  roles/default/kiali-deploy/defaults/main.yml
  roles/default/kiali-deploy/templates/kubernetes/deployment.yaml
  roles/default/kiali-deploy/templates/openshift/deployment.yaml
Labels: requires helm chart PR

#433 [molecule] test with default server image
  molecule/accessible-namespaces-test/kiali-cr.yaml
  molecule/accessible-namespaces-test/molecule.yml
  molecule/affinity-tolerations-resources-test/kiali-cr.yaml
  molecule/affinity-tolerations-resources-test/molecule.yml
  molecule/api-test/dashboards.test.yaml
  molecule/api-test/kiali-cr.yaml
  molecule/api-test/molecule.yml
  molecule/asserts/configmap_asserts.yml
  molecule/config-values-test/kiali-cr.yaml
  molecule/config-values-test/molecule.yml
  molecule/default-namespace-test/kiali-cr.yaml
  molecule/default-namespace-test/molecule.yml
  molecule/default/molecule.yml
  molecule/grafana-test/kiali-cr.yaml
  molecule/grafana-test/molecule.yml
  molecule/header-auth-test/kiali-cr.yaml
  molecule/header-auth-test/molecule.yml
  molecule/instance-name-test/kiali-cr.yaml
  molecule/instance-name-test/molecule.yml
  molecule/jaeger-test/kiali-cr.yaml
  molecule/jaeger-test/molecule.yml
  molecule/kiali-cr.yaml
  molecule/metrics-test/kiali-cr.yaml
  molecule/metrics-test/molecule.yml
  molecule/null-cr-values-test/kiali-cr.yaml
  molecule/null-cr-values-test/molecule.yml
  molecule/only-view-only-mode-test/kiali-cr.yaml
  molecule/only-view-only-mode-test/molecule.yml
  molecule/openid-test/kiali-cr.yaml
  molecule/openid-test/molecule.yml
  molecule/openshift-auth-test/kiali-cr.yaml
  molecule/openshift-auth-test/molecule.yml
  molecule/os-console-links-test/kiali-cr.yaml
  molecule/os-console-links-test/molecule.yml
  molecule/read-certs-secrets-test/kiali-cr.yaml
  molecule/read-certs-secrets-test/molecule.yml
  molecule/roles-test/molecule.yml
  molecule/rolling-restart-test/kiali-cr.yaml
  molecule/rolling-restart-test/molecule.yml
  molecule/token-test/kiali-cr.yaml
  molecule/token-test/molecule.yml
Labels: requires server PR, backport/v1.36

#435 [molecule] get tests to pass again
  molecule/accessible-namespaces-test/converge.yml
  molecule/common/purge-prometheus-data.yml
  molecule/common/query-prometheus.yml
  molecule/instance-name-test/converge.yml
  molecule/null-cr-values-test/converge.yml
Labels: area/testing, backport/v1.36
