Repository kiali/kiali-operator, pull requests merged in 2021-06, with the labels that each got.

#325 move to CRD v1
  manifests/kiali-ossm/manifests/kiali.crd.yaml
  manifests/kiali-ossm/manifests/kiali.monitoringdashboards.crd.yaml
  roles/v1.12/kiali-deploy/tasks/main.yml
  roles/v1.24/kiali-deploy/tasks/main.yml
Labels: team/saturn

#252 fix the Ingress apiVersion so it isn't a deprecated version
  molecule/instance-name-test/converge.yml
  roles/default/kiali-deploy/tasks/kubernetes/k8s-main.yml
  roles/default/kiali-deploy/templates/kubernetes/ingress.yaml
  roles/default/kiali-remove/tasks/main.yml
Labels: helm charts changes required, team/saturn

#326 consolidate dashboards
  DEVELOPING.adoc
  deploy/kiali/kiali_cr.yaml
  dev-playbook-config/dev-hosts.yaml
  dev-playbook-config/dev-kiali-cr.yaml
  manifests/kiali-community/1.36.0/manifests/kiali.v1.36.0.clusterserviceversion.yaml
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
  manifests/kiali-upstream/1.36.0/manifests/kiali.v1.36.0.clusterserviceversion.yaml
  molecule/accessible-namespaces-test/kiali-cr.yaml
  molecule/affinity-tolerations-resources-test/kiali-cr.yaml
  molecule/api-test/dashboards.test.yaml
  molecule/api-test/kiali-cr.yaml
  molecule/config-values-test/converge.yml
  molecule/default-namespace-test/kiali-cr.yaml
  molecule/default/destroy.yml
  molecule/header-auth-test/kiali-cr.yaml
  molecule/instance-name-test/kiali-cr.yaml
  molecule/kiali-cr.yaml
  molecule/metrics-test/kiali-cr.yaml
  molecule/null-cr-values-test/converge.yml
  molecule/null-cr-values-test/kiali-cr.yaml
  molecule/only-view-only-mode-test/kiali-cr.yaml
  molecule/openid-test/kiali-cr.yaml
  molecule/openshift-auth-test/kiali-cr.yaml
  molecule/os-console-links-test/kiali-cr.yaml
  molecule/rolling-restart-test/kiali-cr.yaml
  roles/default/kiali-deploy/defaults/main.yml
  roles/default/kiali-deploy/tasks/main.yml
  roles/default/kiali-deploy/templates/dashboards/envoy.yaml
  roles/default/kiali-deploy/templates/dashboards/go.yaml
  roles/default/kiali-deploy/templates/dashboards/kiali.yaml
  roles/default/kiali-deploy/templates/dashboards/micrometer-1.0.6-jvm-pool.yaml
  roles/default/kiali-deploy/templates/dashboards/micrometer-1.0.6-jvm.yaml
  roles/default/kiali-deploy/templates/dashboards/micrometer-1.1-jvm.yaml
  roles/default/kiali-deploy/templates/dashboards/microprofile-1.1.yaml
  roles/default/kiali-deploy/templates/dashboards/microprofile-x.y.yaml
  roles/default/kiali-deploy/templates/dashboards/nodejs.yaml
  roles/default/kiali-deploy/templates/dashboards/quarkus.yaml
  roles/default/kiali-deploy/templates/dashboards/springboot-jvm-pool.yaml
  roles/default/kiali-deploy/templates/dashboards/springboot-jvm.yaml
  roles/default/kiali-deploy/templates/dashboards/springboot-tomcat.yaml
  roles/default/kiali-deploy/templates/dashboards/thorntail.yaml
  roles/default/kiali-deploy/templates/dashboards/tomcat.yaml
  roles/default/kiali-deploy/templates/dashboards/vertx-client.yaml
  roles/default/kiali-deploy/templates/dashboards/vertx-eventbus.yaml
  roles/default/kiali-deploy/templates/dashboards/vertx-jvm.yaml
  roles/default/kiali-deploy/templates/dashboards/vertx-pool.yaml
  roles/default/kiali-deploy/templates/dashboards/vertx-server.yaml
  roles/default/kiali-deploy/templates/kubernetes/deployment.yaml
  roles/default/kiali-deploy/templates/kubernetes/role-viewer.yaml
  roles/default/kiali-deploy/templates/kubernetes/role.yaml
  roles/default/kiali-deploy/templates/openshift/deployment.yaml
  roles/default/kiali-deploy/templates/openshift/role-viewer.yaml
  roles/default/kiali-deploy/templates/openshift/role.yaml
  roles/default/kiali-deploy/vars/main.yml
  roles/default/kiali-remove/tasks/main.yml
Labels: backend changes required, helm charts changes required, team/saturn

#329 [v1.24] fix default image name
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
Labels: team/saturn

#332 remove istio_component_namespaces config
  deploy/kiali/kiali_cr.yaml
  molecule/null-cr-values-test/kiali-cr.yaml
  roles/default/kiali-deploy/defaults/main.yml
  roles/default/kiali-deploy/tasks/main.yml
  roles/default/kiali-deploy/vars/main.yml
Labels: backend changes required, team/saturn

#333 Mount the "kiali-cabundle" configmap, if present (Kubernetes)
  roles/default/kiali-deploy/templates/kubernetes/deployment.yaml
Labels: team/saturn

#335 support the case when OLM is installed in a non-OpenShift environment
  molecule/accessible-namespaces-test/molecule.yml
  molecule/affinity-tolerations-resources-test/molecule.yml
  molecule/api-test/dashboards.test.yaml
  molecule/api-test/molecule.yml
  molecule/config-values-test/molecule.yml
  molecule/default-namespace-test/molecule.yml
  molecule/default/molecule.yml
  molecule/default/prepare.yml
  molecule/header-auth-test/molecule.yml
  molecule/instance-name-test/molecule.yml
  molecule/metrics-test/molecule.yml
  molecule/null-cr-values-test/molecule.yml
  molecule/only-view-only-mode-test/molecule.yml
  molecule/openid-test/molecule.yml
  molecule/openshift-auth-test/molecule.yml
  molecule/os-console-links-test/molecule.yml
  molecule/roles-test/molecule.yml
  molecule/rolling-restart-test/molecule.yml
  molecule/token-test/molecule.yml
Labels: team/saturn

#337 [molecule] move from community.kubernetes to kubernetes.core.k8s ansible collection
  DEVELOPING.adoc
  molecule/accessible-namespaces-test/converge.yml
  molecule/accessible-namespaces-test/molecule.yml
  molecule/affinity-tolerations-resources-test/converge.yml
  molecule/affinity-tolerations-resources-test/molecule.yml
  molecule/api-test/cleanup.yml
  molecule/api-test/converge.yml
  molecule/api-test/create-simple-mesh.yml
  molecule/api-test/delete-simple-mesh.yml
  molecule/api-test/molecule.yml
  molecule/common/purge-prometheus-data.yml
  molecule/common/tasks.yml
  molecule/config-values-test/converge.yml
  molecule/config-values-test/molecule.yml
  molecule/default-namespace-test/converge.yml
  molecule/default-namespace-test/molecule.yml
  molecule/default/cleanup.yml
  molecule/default/converge.yml
  molecule/default/destroy.yml
  molecule/default/molecule.yml
  molecule/default/prepare.yml
  molecule/docker/Dockerfile
  molecule/header-auth-test/converge.yml
  molecule/header-auth-test/molecule.yml
  molecule/instance-name-test/converge.yml
  molecule/instance-name-test/destroy-instance-name-test.yml
  molecule/instance-name-test/molecule.yml
  molecule/instance-name-test/prepare-instance-name-test.yml
  molecule/instance-name-test/process-namespace.yml
  molecule/metrics-test/converge.yml
  molecule/metrics-test/molecule.yml
  molecule/null-cr-values-test/converge.yml
  molecule/null-cr-values-test/molecule.yml
  molecule/only-view-only-mode-test/converge.yml
  molecule/only-view-only-mode-test/molecule.yml
  molecule/openid-test/converge.yml
  molecule/openid-test/molecule.yml
  molecule/openshift-auth-test/converge.yml
  molecule/openshift-auth-test/molecule.yml
  molecule/os-console-links-test/converge.yml
  molecule/os-console-links-test/molecule.yml
  molecule/requirements.txt
  molecule/roles-test/converge.yml
  molecule/roles-test/molecule.yml
  molecule/rolling-restart-test/converge.yml
  molecule/rolling-restart-test/molecule.yml
  molecule/token-test/converge.yml
  molecule/token-test/molecule.yml
Labels: area/testing, backport/v1.36, team/saturn

#339 add the new v1.36 ansible role to the operator
  playbooks/default-supported-images.yml
  roles/v1.36/kiali-deploy/defaults/main.yml
  roles/v1.36/kiali-deploy/filter_plugins/only_accessible_namespaces.py
  roles/v1.36/kiali-deploy/filter_plugins/stripnone.py
  roles/v1.36/kiali-deploy/meta/main.yml
  roles/v1.36/kiali-deploy/tasks/kubernetes/k8s-main.yml
  roles/v1.36/kiali-deploy/tasks/main.yml
  roles/v1.36/kiali-deploy/tasks/openshift/os-get-kiali-route-url.yml
  roles/v1.36/kiali-deploy/tasks/openshift/os-main.yml
  roles/v1.36/kiali-deploy/tasks/process-resource.yml
  roles/v1.36/kiali-deploy/tasks/remove-clusterroles.yml
  roles/v1.36/kiali-deploy/tasks/remove-roles.yml
  roles/v1.36/kiali-deploy/tasks/update-status-progress.yml
  roles/v1.36/kiali-deploy/tasks/update-status.yml
  roles/v1.36/kiali-deploy/templates/kubernetes/configmap.yaml
  roles/v1.36/kiali-deploy/templates/kubernetes/deployment.yaml
  roles/v1.36/kiali-deploy/templates/kubernetes/hpa.yaml
  roles/v1.36/kiali-deploy/templates/kubernetes/ingress.yaml
  roles/v1.36/kiali-deploy/templates/kubernetes/role-controlplane.yaml
  roles/v1.36/kiali-deploy/templates/kubernetes/role-viewer.yaml
  roles/v1.36/kiali-deploy/templates/kubernetes/role.yaml
  roles/v1.36/kiali-deploy/templates/kubernetes/rolebinding-controlplane.yaml
  roles/v1.36/kiali-deploy/templates/kubernetes/rolebinding.yaml
  roles/v1.36/kiali-deploy/templates/kubernetes/service.yaml
  roles/v1.36/kiali-deploy/templates/kubernetes/serviceaccount.yaml
  roles/v1.36/kiali-deploy/templates/openshift/cabundle.yaml
  roles/v1.36/kiali-deploy/templates/openshift/configmap.yaml
  roles/v1.36/kiali-deploy/templates/openshift/console-links.yaml
  roles/v1.36/kiali-deploy/templates/openshift/deployment.yaml
  roles/v1.36/kiali-deploy/templates/openshift/hpa.yaml
  roles/v1.36/kiali-deploy/templates/openshift/oauth.yaml
  roles/v1.36/kiali-deploy/templates/openshift/role-controlplane.yaml
  roles/v1.36/kiali-deploy/templates/openshift/role-viewer.yaml
  roles/v1.36/kiali-deploy/templates/openshift/role.yaml
  roles/v1.36/kiali-deploy/templates/openshift/rolebinding-controlplane.yaml
  roles/v1.36/kiali-deploy/templates/openshift/rolebinding.yaml
  roles/v1.36/kiali-deploy/templates/openshift/route.yaml
  roles/v1.36/kiali-deploy/templates/openshift/service.yaml
  roles/v1.36/kiali-deploy/templates/openshift/serviceaccount.yaml
  roles/v1.36/kiali-deploy/vars/main.yml
  roles/v1.36/kiali-remove/defaults/main.yml
  roles/v1.36/kiali-remove/filter_plugins/stripnone.py
  roles/v1.36/kiali-remove/meta/main.yml
  roles/v1.36/kiali-remove/tasks/main.yml
  roles/v1.36/kiali-remove/tasks/remove-clusterroles.yml
  roles/v1.36/kiali-remove/vars/main.yml
Labels: backport/v1.36, team/saturn

#340 [v1.36] add the new v1.36 ansible role to the operator
  playbooks/default-supported-images.yml
  roles/v1.36/kiali-deploy/defaults/main.yml
  roles/v1.36/kiali-deploy/filter_plugins/only_accessible_namespaces.py
  roles/v1.36/kiali-deploy/filter_plugins/stripnone.py
  roles/v1.36/kiali-deploy/meta/main.yml
  roles/v1.36/kiali-deploy/tasks/kubernetes/k8s-main.yml
  roles/v1.36/kiali-deploy/tasks/main.yml
  roles/v1.36/kiali-deploy/tasks/openshift/os-get-kiali-route-url.yml
  roles/v1.36/kiali-deploy/tasks/openshift/os-main.yml
  roles/v1.36/kiali-deploy/tasks/process-resource.yml
  roles/v1.36/kiali-deploy/tasks/remove-clusterroles.yml
  roles/v1.36/kiali-deploy/tasks/remove-roles.yml
  roles/v1.36/kiali-deploy/tasks/update-status-progress.yml
  roles/v1.36/kiali-deploy/tasks/update-status.yml
  roles/v1.36/kiali-deploy/templates/kubernetes/configmap.yaml
  roles/v1.36/kiali-deploy/templates/kubernetes/deployment.yaml
  roles/v1.36/kiali-deploy/templates/kubernetes/hpa.yaml
  roles/v1.36/kiali-deploy/templates/kubernetes/ingress.yaml
  roles/v1.36/kiali-deploy/templates/kubernetes/role-controlplane.yaml
  roles/v1.36/kiali-deploy/templates/kubernetes/role-viewer.yaml
  roles/v1.36/kiali-deploy/templates/kubernetes/role.yaml
  roles/v1.36/kiali-deploy/templates/kubernetes/rolebinding-controlplane.yaml
  roles/v1.36/kiali-deploy/templates/kubernetes/rolebinding.yaml
  roles/v1.36/kiali-deploy/templates/kubernetes/service.yaml
  roles/v1.36/kiali-deploy/templates/kubernetes/serviceaccount.yaml
  roles/v1.36/kiali-deploy/templates/openshift/cabundle.yaml
  roles/v1.36/kiali-deploy/templates/openshift/configmap.yaml
  roles/v1.36/kiali-deploy/templates/openshift/console-links.yaml
  roles/v1.36/kiali-deploy/templates/openshift/deployment.yaml
  roles/v1.36/kiali-deploy/templates/openshift/hpa.yaml
  roles/v1.36/kiali-deploy/templates/openshift/oauth.yaml
  roles/v1.36/kiali-deploy/templates/openshift/role-controlplane.yaml
  roles/v1.36/kiali-deploy/templates/openshift/role-viewer.yaml
  roles/v1.36/kiali-deploy/templates/openshift/role.yaml
  roles/v1.36/kiali-deploy/templates/openshift/rolebinding-controlplane.yaml
  roles/v1.36/kiali-deploy/templates/openshift/rolebinding.yaml
  roles/v1.36/kiali-deploy/templates/openshift/route.yaml
  roles/v1.36/kiali-deploy/templates/openshift/service.yaml
  roles/v1.36/kiali-deploy/templates/openshift/serviceaccount.yaml
  roles/v1.36/kiali-deploy/vars/main.yml
  roles/v1.36/kiali-remove/defaults/main.yml
  roles/v1.36/kiali-remove/filter_plugins/stripnone.py
  roles/v1.36/kiali-remove/meta/main.yml
  roles/v1.36/kiali-remove/tasks/main.yml
  roles/v1.36/kiali-remove/tasks/remove-clusterroles.yml
  roles/v1.36/kiali-remove/vars/main.yml
Labels: team/saturn

#343 [molecule] wait for test namespace to be actually deleted
  molecule/api-test/delete-simple-mesh.yml
Labels: area/testing, backport/v1.36, team/saturn

#344 [v1.36][molecule] wait for test namespace to be actually deleted
  molecule/api-test/delete-simple-mesh.yml
Labels: area/testing, team/saturn

#346 [v1.36] related_images should refer to 1.36
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
Labels: team/saturn

#345 related_images should refer to 1.36
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
Labels: backport/v1.36, team/saturn
