Repository kiali/kiali-operator, pull requests merged in 2023-05, with the labels that each got.

#641 provide permission to support override_yaml.spec.host on openshift
  manifests/kiali-community/1.68.0/manifests/kiali.v1.68.0.clusterserviceversion.yaml
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
  manifests/kiali-upstream/1.68.0/manifests/kiali.v1.68.0.clusterserviceversion.yaml
Labels: requires helm chart PR

#651 [v1.57] set oauth redirect to route with non-standard port
  roles/default/kiali-deploy/templates/openshift/oauth.yaml
  roles/v1.57/kiali-deploy/templates/openshift/oauth.yaml
Labels: do not merge

#649 set oauth redirect to route with non-standard port
  roles/default/kiali-deploy/templates/openshift/oauth.yaml
  roles/v1.57/kiali-deploy/templates/openshift/oauth.yaml
  roles/v1.65/kiali-deploy/templates/openshift/oauth.yaml
Labels: requires server PR, requires helm chart PR

#644 Add new server config clusterName
  crd-docs/crd/kiali.io_kialis.yaml
  roles/default/kiali-deploy/defaults/main.yml
Labels: enhancement
