Repository kiali/kiali-operator, pull requests merged in 2024-12, with the labels that each got.

#848 [Tempo] Add tempo cache config option
  crd-docs/cr/kiali.io_v1alpha1_kiali.yaml
  crd-docs/crd/kiali.io_kialis.yaml
  roles/default/kiali-deploy/defaults/main.yml
Labels: enhancement

#853 Add oauth-cabundle configmap to bundle mount
  roles/default/kiali-deploy/templates/openshift/deployment.yaml
Labels: requires server PR

#851 Add new graph setting for the animation style
  crd-docs/cr/kiali.io_v1alpha1_kiali.yaml
  crd-docs/crd/kiali.io_kialis.yaml
  roles/default/kiali-deploy/defaults/main.yml
Labels: test: n/a

#856 increase signing key length
  roles/default/kiali-deploy/tasks/main.yml
Labels: test: n/a

#857 [operator] bump operator base image to 1.36.0
  Makefile
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
  manifests/kiali-upstream/2.4.0/manifests/kiali.v2.4.0.clusterserviceversion.yaml
Labels: requires helm chart PR
