Repository kiali/kiali-operator, pull requests merged in 2024-11, with the labels that each got.

#843 make some changes for best practices
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
  manifests/kiali-upstream/2.2.0/manifests/kiali.v2.2.0.clusterserviceversion.yaml
  roles/default/kiali-deploy/templates/kubernetes/deployment.yaml
  roles/default/kiali-deploy/templates/openshift/deployment.yaml
Labels: enhancement, requires helm chart PR

#847 be able to configure server liveness/readiness/startup probe
  crd-docs/cr/kiali.io_v1alpha1_kiali.yaml
  crd-docs/crd/kiali.io_kialis.yaml
  molecule/config-values-test/converge.yml
  roles/default/kiali-deploy/defaults/main.yml
  roles/default/kiali-deploy/templates/kubernetes/deployment.yaml
  roles/default/kiali-deploy/templates/openshift/deployment.yaml
Labels: test: molecule

#849 do not allow multiple Kiali CRs with CWA=true and the same instance_name
  roles/default/kiali-deploy/tasks/main.yml
Labels: requires docs PR

#850 Enable the release schedule in github actions
  .github/workflows/release.yml
Labels: test: n/a
