Repository kiali/kiali-operator, pull requests merged in 2024-07, with the labels that each got.

#790 Disable tracing by default
  crd-docs/cr/kiali.io_v1alpha1_kiali.yaml
  molecule/jaeger-test/kiali-cr.yaml
  roles/default/kiali-deploy/defaults/main.yml
Labels: enhancement

#791 Upgrade github actions to Node 20
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
Labels: test: n/a

#798 ignore replicas if HPA is set
  crd-docs/crd/kiali.io_kialis.yaml
  molecule/affinity-tolerations-resources-test/converge.yml
  molecule/affinity-tolerations-resources-test/kiali-cr.yaml
  molecule/asserts/pod_asserts.yml
  molecule/common/wait_for_kiali_running.yml
  roles/default/kiali-deploy/templates/kubernetes/deployment.yaml
  roles/default/kiali-deploy/templates/openshift/deployment.yaml
Labels: requires helm chart PR
