Repository kiali/kiali-operator, pull requests merged in 2024-06, with the labels that each got.

#772 Add config for the server timeout
  crd-docs/cr/kiali.io_v1alpha1_kiali.yaml
  crd-docs/crd/kiali.io_kialis.yaml
  roles/default/kiali-deploy/defaults/main.yml
Labels: enhancement

#774 do not attempt to mount a cluster secret if none were provided.
  crd-docs/cr/kiali.io_v1alpha1_kiali.yaml
  crd-docs/crd/kiali.io_kialis.yaml
  roles/default/kiali-deploy/defaults/main.yml
  roles/default/kiali-deploy/tasks/main.yml
Labels: requires helm chart PR

#775 [v1.73] Add config for the server timeout
  crd-docs/cr/kiali.io_v1alpha1_kiali.yaml
  crd-docs/crd/kiali.io_kialis.yaml
  roles/default/kiali-deploy/defaults/main.yml
Labels: enhancement

#781 fix openid-test molecule test due to MC changes
  molecule/openid-test/converge.yml
Labels: test: molecule
