Repository kiali/kiali-operator, pull requests merged in 2024-03, with the labels that each got.

#747 Add new health_check_url for tracing
  crd-docs/cr/kiali.io_v1alpha1_kiali.yaml
  crd-docs/crd/kiali.io_kialis.yaml
  roles/default/kiali-deploy/defaults/main.yml
Labels: enhancement

#748 operator support for mounting secrets from CSI secret store
  crd-docs/cr/kiali.io_v1alpha1_kiali.yaml
  crd-docs/crd/kiali.io_kialis.yaml
  roles/default/kiali-deploy/tasks/snake_camel_case.yaml
  roles/default/kiali-deploy/templates/kubernetes/deployment.yaml
  roles/default/kiali-deploy/templates/openshift/deployment.yaml
Labels: requires helm chart PR

#749 New Tempo grafana datasource settings
  crd-docs/cr/kiali.io_v1alpha1_kiali.yaml
  crd-docs/crd/kiali.io_kialis.yaml
  roles/default/kiali-deploy/defaults/main.yml
Labels: docs, enhancement

#753 remove verbose_mode that has been deprecated
  crd-docs/cr/kiali.io_v1alpha1_kiali.yaml
  crd-docs/crd/kiali.io_kialis.yaml
  roles/default/kiali-deploy/templates/kubernetes/deployment.yaml
  roles/default/kiali-deploy/templates/openshift/deployment.yaml
Labels: requires server PR, requires helm chart PR
