Repository kiali/kiali-operator, pull requests merged in 2024-10, with the labels that each got.

#828 be able to put username in secrets
  crd-docs/crd/kiali.io_kialis.yaml
  roles/default/kiali-deploy/tasks/main.yml
Labels: requires server PR

#829 be able to set custom env vars on server pod
  crd-docs/cr/kiali.io_v1alpha1_kiali.yaml
  crd-docs/crd/kiali.io_kialis.yaml
  molecule/config-values-test/converge.yml
  roles/default/kiali-deploy/defaults/main.yml
  roles/default/kiali-deploy/templates/kubernetes/deployment.yaml
  roles/default/kiali-deploy/templates/openshift/deployment.yaml
Labels: requires helm chart PR

#830 Add url format in tempo config
  crd-docs/cr/kiali.io_v1alpha1_kiali.yaml
  crd-docs/crd/kiali.io_kialis.yaml
  roles/default/kiali-deploy/defaults/main.yml
Labels: enhancement

#835 [operator] bump operator base image to 4.17 / 1.35.0
  Makefile
  build/Dockerfile
  requirements.yml
Labels: test: n/a
