Repository kiali/kiali-operator, pull requests merged in 2025-01, with the labels that each got.

#861 Fix operator multi-arch build with updated buildkit and binfmt
  Makefile
Labels: test: n/a

#867 Add relatedImages section in clusterserviceversion
  DEVELOPING.adoc
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
Labels: test: n/a

#868 [v2.4] Add relatedImages section in clusterserviceversion
  DEVELOPING.adoc
  manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
Labels: test: n/a

#865 be able to configure /api endpoint to require credentials
  crd-docs/cr/kiali.io_v1alpha1_kiali.yaml
  crd-docs/crd/kiali.io_kialis.yaml
  roles/default/kiali-deploy/defaults/main.yml
  roles/v2.4/kiali-deploy/defaults/main.yml
Labels: requires server PR

#873 support topologySpreadConstraints in Deployment config
  crd-docs/cr/kiali.io_v1alpha1_kiali.yaml
  crd-docs/crd/kiali.io_kialis.yaml
  molecule/affinity-tolerations-resources-test/converge.yml
  molecule/affinity-tolerations-resources-test/set-affinity-tolerations-resources.yml
  roles/default/kiali-deploy/defaults/main.yml
  roles/default/kiali-deploy/tasks/snake_camel_case.yaml
  roles/default/kiali-deploy/templates/kubernetes/deployment.yaml
  roles/default/kiali-deploy/templates/openshift/deployment.yaml
Labels: requires helm chart PR, test: molecule
